window.env = {
  "SHELL": "/bin/bash",
  "npm_package_dependencies_csv_parse": "^4.16.3",
  "COLORTERM": "truecolor",
  "npm_package_dependencies__types_react": "^17.0.0",
  "SUDO_GID": "1000",
  "npm_package_browserslist_development_0": "last 1 chrome version",
  "npm_package_browserslist_development_1": "last 1 firefox version",
  "npm_package_browserslist_development_2": "last 1 safari version",
  "npm_package_dependencies_react_scripts": "4.0.3",
  "NODE": "/usr/bin/node",
  "npm_config_ignore_scripts": "",
  "LC_ADDRESS": "pl_PL.UTF-8",
  "npm_package_eslintConfig_extends_0": "react-app",
  "npm_package_eslintConfig_extends_1": "react-app/jest",
  "LC_NAME": "pl_PL.UTF-8",
  "npm_package_private": "true",
  "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"start\"],\"original\":[\"start\"]}",
  "SUDO_COMMAND": "/usr/bin/yarn start",
  "npm_config_bin_links": "true",
  "LC_MONETARY": "pl_PL.UTF-8",
  "SUDO_USER": "pacto",
  "npm_package_dependencies_axios": "^0.21.4",
  "PWD": "/home/pacto/Documents/bulk-selling-tool",
  "npm_config_save_prefix": "^",
  "LOGNAME": "root",
  "npm_package_readmeFilename": "README.md",
  "npm_package_dependencies_react": "^17.0.2",
  "npm_package_dependencies_web_vitals": "^1.0.1",
  "npm_package_scripts_build": "react-scripts build",
  "_": "/home/pacto/Documents/bulk-selling-tool/node_modules/.bin/react-dotenv",
  "XAUTHORITY": "/home/pacto/.Xauthority",
  "HOME": "/root",
  "npm_config_version_git_tag": "true",
  "LC_PAPER": "pl_PL.UTF-8",
  "LANG": "en_US.utf8",
  "npm_package_dependencies__types_styled_components": "^5.1.14",
  "npm_package_dependencies__types_react_dom": "^17.0.0",
  "npm_config_init_license": "MIT",
  "npm_package_version": "0.1.0",
  "npm_config_version_commit_hooks": "true",
  "npm_package_dependencies_styled_components": "^5.3.1",
  "npm_package_dependencies__testing_library_jest_dom": "^5.11.4",
  "INIT_CWD": "/home/pacto/Documents/bulk-selling-tool",
  "npm_lifecycle_script": "react-dotenv && export PORT=80 && react-scripts start",
  "npm_config_version_tag_prefix": "v",
  "YARN_WRAP_OUTPUT": "false",
  "npm_package_dependencies_react_icons": "^4.2.0",
  "TERM": "termite",
  "LC_IDENTIFICATION": "pl_PL.UTF-8",
  "npm_package_name": "bulk-selling-tool",
  "npm_package_dependencies__types_node": "^12.0.0",
  "npm_package_scripts_eject": "react-scripts eject",
  "USER": "root",
  "npm_package_dependencies_react_dom": "^17.0.2",
  "DISPLAY": ":0.0",
  "npm_lifecycle_event": "start",
  "SHLVL": "1",
  "npm_config_version_git_sign": "",
  "npm_package_dependencies__testing_library_user_event": "^12.1.10",
  "npm_config_version_git_message": "v%s",
  "LC_TELEPHONE": "pl_PL.UTF-8",
  "LC_MEASUREMENT": "pl_PL.UTF-8",
  "npm_config_user_agent": "yarn/1.22.11 npm/? node/v16.8.0 linux x64",
  "npm_execpath": "/usr/lib/node_modules/yarn/bin/yarn.js",
  "npm_package_scripts_test": "react-scripts test",
  "npm_config_strict_ssl": "true",
  "LC_TIME": "pl_PL.UTF-8",
  "npm_package_dependencies_typescript": "^4.1.2",
  "npm_package_dependencies__types_jest": "^26.0.15",
  "npm_package_browserslist_production_2": "not op_mini all",
  "npm_package_scripts_start": "react-dotenv && export PORT=80 && react-scripts start",
  "npm_package_browserslist_production_0": ">0.2%",
  "npm_package_browserslist_production_1": "not dead",
  "PATH": "/tmp/yarn--1631265875421-0.9645093785106971:/home/pacto/Documents/bulk-selling-tool/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/home/pacto/.autojump/bin:/home/pacto/.autojump/bin:/home/pacto/.autojump/bin:/home/pacto/.local/bin:/home/pacto/.autojump/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin",
  "SUDO_UID": "1000",
  "MAIL": "/var/mail/root",
  "npm_config_registry": "https://registry.yarnpkg.com",
  "npm_config_ignore_optional": "",
  "npm_package_dependencies__testing_library_react": "^11.1.0",
  "npm_package_dependencies__types_react_icons": "^3.0.0",
  "npm_node_execpath": "/usr/bin/node",
  "LC_NUMERIC": "pl_PL.UTF-8",
  "npm_package_dependencies_react_dotenv": "^0.1.3",
  "npm_config_init_version": "1.0.0"
};