export const itemFilter = {
  fragments: [
    {
      name: "Breachstones",
      items: [
        "Chayula's Pure Breachstone",
        "Chayula's Breachstone",
        "Chayula's Enriched Breachstone",
        "Uul-Netol's Pure Breachstone",
        "Chayula's Charged Breachstone",
        "Uul-Netol's Enriched Breachstone",
        "Xoph's Pure Breachstone",
        "Tul's Pure Breachstone",
        "Esh's Pure Breachstone",
        "Uul-Netol's Breachstone",
        "Uul-Netol's Charged Breachstone",
        "Xoph's Enriched Breachstone",
        "Tul's Enriched Breachstone",
        "Esh's Enriched Breachstone",
        "Tul's Charged Breachstone",
        "Xoph's Charged Breachstone",
        "Esh's Charged Breachstone",
        "Xoph's Breachstone",
        "Tul's Breachstone",
        "Esh's Breachstone",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaEZyYWdtZW50c0NoYW9zIiwic2NhbGUiOjF9XQ/4c99b7dd49/BreachFragmentsChaos.png",
    },
    {
      name: "Emblems",
      items: [
        "Timeless Maraketh Emblem",
        "Timeless Templar Emblem",
        "Unrelenting Timeless Karui Emblem",
        "Timeless Vaal Emblem",
        "Timeless Karui Emblem",
        "Unrelenting Timeless Maraketh Emblem",
        "Unrelenting Timeless Eternal Emblem",
        "Unrelenting Timeless Templar Emblem",
        "Unrelenting Timeless Vaal Emblem",
        "Timeless Eternal Emblem",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9NYXJha2V0aEZyYWdtZW50Iiwic2NhbGUiOjF9XQ/a81c4968ab/MarakethFragment.png",
    },
    {
      name: "Atziri",
      items: [
        "Sacrifice at Midnight",
        "Sacrifice at Noon",
        "Sacrifice at Dawn",
        "Sacrifice at Dusk",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9WYWFsQ29tcGxldGUiLCJzY2FsZSI6MX1d/63035d86d7/VaalComplete.png",
    },
    {
      name: "Uber Atziri",
      items: ["Mortal Rage", "Mortal Ignorance", "Mortal Hope", "Mortal Grief"],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9VYmVyVmFhbENvbXBsZXRlIiwic2NhbGUiOjF9XQ/994d9e2821/UberVaalComplete.png",
    },
    {
      name: "Elder",
      items: [
        "Fragment of Enslavement",
        "Fragment of Eradication",
        "Fragment of Constriction",
        "Fragment of Purification",
        "Fragment of Terror",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9FbGRlckNvbXBsZXRlIiwic2NhbGUiOjF9XQ/6db44597fe/ElderComplete.png",
    },
    {
      name: "Shaper",
      items: [
        "Fragment of the Hydra",
        "Fragment of the Phoenix",
        "Fragment of the Minotaur",
        "Fragment of the Chimera",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9TaGFwZXJDb21wbGV0ZSIsInNjYWxlIjoxfV0/ace686004d/ShaperComplete.png",
    },
    {
      name: "Uber Elder",
      items: [
        "Fragment of Knowledge",
        "Fragment of Shape",
        "Fragment of Terror",
        "Fragment of Emptiness",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9VYmVyRWxkZXJDb21wbGV0ZSIsInNjYWxlIjoxfV0/715e041869/UberElderComplete.png",
    },
  ],
  currencyFilter: {
    items: [
      "Mirror of Kalandra",
      "Mirror Shard",
      "Awakener's Orb",
      "Maven's Orb",
      "Hunter's Exalted Orb",
      "Exalted Orb",
      "Tempering Orb",
      "Warlord's Exalted Orb",
      "Redeemer's Exalted Orb",
      "Crusader's Exalted Orb",
      "Blessing of Chayula",
      "Tainted Divine Teardrop",
      "Secondary Regrading Lens",
      "Prime Regrading Lens",
      "Tailoring Orb",
      "Elevated Sextant",
      "Blessing of Xoph",
      "Tainted Mythic Orb",
      "Orb of Unmaking",
      "Divine Orb",
      "Blessing of Uul-Netol",
      "Ritual Vessel",
      "Blessing of Tul",
      "Blessing of Esh",
      "Kalguuran Delirium Orb",
      "Ancient Orb",
      "Exalted Shard",
      "Prismatic Catalyst",
      "Tainted Orb of Fusing",
      "Tainted Exalted Orb",
      "Orb of Annulment",
      "Sacred Orb",
      "Tainted Chaos Orb",
      "Tainted Blessing",
      "Fertile Catalyst",
      "Harbinger's Orb",
      "Veiled Chaos Orb",
      "Tainted Chromatic Orb",
      "Awakened Sextant",
      "Tempering Catalyst",
      "Annulment Shard",
      "Intrinsic Catalyst",
      "Unstable Catalyst",
      "Infused Engineer's Orb",
      "Orb of Regret",
      "Gemcutter's Prism",
      "Stacked Deck",
      "Turbulent Catalyst",
      "Tainted Jeweller's Orb",
      "Prime Sextant",
      "Vaal Orb",
      "Regal Orb",
      "Abrasive Catalyst",
      "Accelerating Catalyst",
      "Noxious Catalyst",
      "Orb of Scouring",
      "Blessed Orb",
      "Tainted Blacksmith's Whetstone",
      "Instilling Orb",
      "Simple Sextant",
      "Orb of Horizons",
      "Imbued Catalyst",
      "Glassblower's Bauble",
      "Tainted Armourer's Scrap",
      "Cartographer's Chisel",
      "Orb of Fusing",
      "Orb of Alteration",
      "Enkindling Orb",
      "Silver Coin",
      "Orb of Alchemy",
      "Orb of Binding",
      "Orb of Chance",
      "Chromatic Orb",
      "Jeweller's Orb",
      "Orb of Augmentation",
      "Blacksmith's Whetstone",
      "Engineer's Orb",
      "Orb of Transmutation",
      "Armourer's Scrap",
    ],
    name: "Currencies",
    icon: "https://web.poecdn.com/image/Art/2DItems/Currency/CurrencyRerollRare.png?scale=1&w=1&h=1",
  },
  fragmentFilter: {
    items: [
      "Simulacrum",
      "Chayula's Pure Breachstone",
      "Timeless Maraketh Emblem",
      "Timeless Templar Emblem",
      "Chayula's Breachstone",
      "The Maven's Writ",
      "Uul-Netol's Pure Breachstone",
      "Fragment of Shape",
      "Uul-Netol's Enriched Breachstone",
      "Fragment of Knowledge",
      "Gift to the Goddess",
      "Uul-Netol's Charged Breachstone",
      "Chayula's Charged Breachstone",
      "Chayula's Enriched Breachstone",
      "Uul-Netol's Breachstone",
      "Xoph's Pure Breachstone",
      "Tul's Pure Breachstone",
      "Esh's Pure Breachstone",
      "Unrelenting Timeless Karui Emblem",
      "Tul's Enriched Breachstone",
      "Esh's Enriched Breachstone",
      "Timeless Vaal Emblem",
      "Xoph's Enriched Breachstone",
      "Tul's Charged Breachstone",
      "Timeless Karui Emblem",
      "Xoph's Charged Breachstone",
      "Unrelenting Timeless Maraketh Emblem",
      "Unrelenting Timeless Eternal Emblem",
      "Unrelenting Timeless Templar Emblem",
      "Unrelenting Timeless Vaal Emblem",
      "Timeless Eternal Emblem",
      "Esh's Charged Breachstone",
      "Tul's Breachstone",
      "Esh's Breachstone",
      "Xoph's Breachstone",
      "Fragment of Eradication",
      "Fragment of Enslavement",
      "Fragment of Constriction",
      "Fragment of Emptiness",
      "Fragment of Purification",
      "Fragment of Terror",
      "Fragment of the Hydra",
      "Fragment of the Phoenix",
      "Fragment of the Minotaur",
      "Fragment of the Chimera",
      "Mortal Ignorance",
      "Volkuur's Key",
      "Mortal Hope",
      "Crescent Splinter",
      "Eber's Key",
      "Yriel's Key",
      "Inya's Key",
      "Mortal Rage",
      "Offering to the Goddess",
      "Mortal Grief",
      "Divine Vessel",
      "Tribute to the Goddess",
      "Dedication to the Goddess",
      "Sacrifice at Midnight",
      "Splinter of Chayula",
      "Sacrifice at Noon",
      "Timeless Templar Splinter",
      "Timeless Maraketh Splinter",
      "Simulacrum Splinter",
      "Sacrifice at Dawn",
      "Splinter of Uul-Netol",
      "Sacrifice at Dusk",
      "Timeless Vaal Splinter",
      "Timeless Karui Splinter",
      "Timeless Eternal Empire Splinter",
      "Splinter of Tul",
      "Splinter of Xoph",
      "Splinter of Esh",
    ],
    name: "Fragments",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaEZyYWdtZW50c0NoYW9zIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/04b5c032f4/BreachFragmentsChaos.png",
  },
  oilFilter: {
    items: [
      "Tainted Oil",
      "Golden Oil",
      "Silver Oil",
      "Opalescent Oil",
      "Crimson Oil",
      "Black Oil",
      "Violet Oil",
      "Sepia Oil",
      "Verdant Oil",
      "Clear Oil",
      "Teal Oil",
      "Amber Oil",
      "Azure Oil",
      "Indigo Oil",
    ],
    name: "Oills",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9Hb2xkZW5PaWwiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/69094a06e9/GoldenOil.png",
  },
  scarabFilter: {
    items: [
      "Winged Reliquary Scarab",
      "Winged Divination Scarab",
      "Winged Legion Scarab",
      "Winged Harbinger Scarab",
      "Winged Abyss Scarab",
      "Winged Ambush Scarab",
      "Winged Blight Scarab",
      "Winged Expedition Scarab",
      "Fenumal Lure",
      "Craicic Lure",
      "Winged Breach Scarab",
      "Gilded Legion Scarab",
      "Gilded Blight Scarab",
      "Gilded Expedition Scarab",
      "Winged Bestiary Scarab",
      "Gilded Harbinger Scarab",
      "Winged Sulphite Scarab",
      "Winged Cartography Scarab",
      "Farric Lure",
      "Polished Expedition Scarab",
      "Gilded Reliquary Scarab",
      "Winged Metamorph Scarab",
      "Winged Elder Scarab",
      "Winged Torment Scarab",
      "Rusted Blight Scarab",
      "Rusted Expedition Scarab",
      "Gilded Breach Scarab",
      "Gilded Bestiary Scarab",
      "Gilded Divination Scarab",
      "Winged Shaper Scarab",
      "Polished Blight Scarab",
      "Gilded Abyss Scarab",
      "Gilded Sulphite Scarab",
      "Polished Bestiary Scarab",
      "Saqawine Lure",
      "Polished Harbinger Scarab",
      "Gilded Ambush Scarab",
      "Gilded Cartography Scarab",
      "Polished Legion Scarab",
      "Gilded Metamorph Scarab",
      "Rusted Bestiary Scarab",
      "Polished Sulphite Scarab",
      "Polished Breach Scarab",
      "Rusted Harbinger Scarab",
      "Rusted Sulphite Scarab",
      "Gilded Torment Scarab",
      "Gilded Shaper Scarab",
      "Polished Cartography Scarab",
      "Gilded Elder Scarab",
      "Polished Divination Scarab",
      "Rusted Legion Scarab",
      "Rusted Cartography Scarab",
      "Rusted Divination Scarab",
      "Rusted Elder Scarab",
      "Rusted Breach Scarab",
      "Rusted Ambush Scarab",
      "Rusted Shaper Scarab",
      "Polished Shaper Scarab",
      "Polished Torment Scarab",
      "Polished Elder Scarab",
      "Polished Reliquary Scarab",
      "Polished Ambush Scarab",
      "Rusted Metamorph Scarab",
      "Polished Metamorph Scarab",
      "Polished Abyss Scarab",
      "Rusted Abyss Scarab",
      "Rusted Reliquary Scarab",
      "Rusted Torment Scarab",
    ],
    name: "Scarabs",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9UaWVyNFNjYXJhYkhhcmJpbmdlcnMiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/81caefbf3f/Tier4ScarabHarbingers.png",
  },
  fossilFilter: {
    items: [
      "Faceted Fossil",
      "Fractured Fossil",
      "Glyphic Fossil",
      "Shuddering Fossil",
      "Bound Fossil",
      "Corroded Fossil",
      "Hollow Fossil",
      "Gilded Fossil",
      "Sanctified Fossil",
      "Bloodstained Fossil",
      "Prismatic Fossil",
      "Tangled Fossil",
      "Perfect Fossil",
      "Aetheric Fossil",
      "Jagged Fossil",
      "Aberrant Fossil",
      "Pristine Fossil",
      "Serrated Fossil",
      "Scorched Fossil",
      "Dense Fossil",
      "Metallic Fossil",
      "Lucent Fossil",
      "Deft Fossil",
      "Fundamental Fossil",
      "Frigid Fossil",
    ],
    name: "Fossils",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRGVsdmUvRmFjZXRlZEZvc3NpbCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/db0aba6238/FacetedFossil.png",
  },
  essenceFilter: {
    items: [
      "Essence of Horror",
      "Essence of Hysteria",
      "Essence of Delirium",
      "Essence of Insanity",
      "Deafening Essence of Contempt",
      "Deafening Essence of Scorn",
      "Deafening Essence of Spite",
      "Deafening Essence of Wrath",
      "Deafening Essence of Rage",
      "Deafening Essence of Woe",
      "Deafening Essence of Dread",
      "Deafening Essence of Envy",
      "Deafening Essence of Greed",
      "Deafening Essence of Zeal",
      "Deafening Essence of Hatred",
      "Deafening Essence of Loathing",
      "Deafening Essence of Misery",
      "Deafening Essence of Sorrow",
      "Deafening Essence of Doubt",
      "Deafening Essence of Fear",
      "Shrieking Essence of Contempt",
      "Shrieking Essence of Scorn",
      "Shrieking Essence of Wrath",
      "Shrieking Essence of Greed",
      "Shrieking Essence of Spite",
      "Shrieking Essence of Woe",
      "Deafening Essence of Anger",
      "Deafening Essence of Anguish",
      "Deafening Essence of Suffering",
      "Deafening Essence of Torment",
      "Shrieking Essence of Dread",
      "Shrieking Essence of Envy",
      "Shrieking Essence of Rage",
      "Shrieking Essence of Sorrow",
      "Shrieking Essence of Zeal",
      "Muttering Essence of Anger",
      "Muttering Essence of Contempt",
      "Muttering Essence of Fear",
      "Muttering Essence of Greed",
      "Muttering Essence of Hatred",
      "Muttering Essence of Sorrow",
      "Muttering Essence of Torment",
      "Muttering Essence of Woe",
      "Remnant of Corruption",
      "Screaming Essence of Anger",
      "Screaming Essence of Contempt",
      "Screaming Essence of Doubt",
      "Screaming Essence of Dread",
      "Screaming Essence of Envy",
      "Screaming Essence of Fear",
      "Screaming Essence of Greed",
      "Screaming Essence of Hatred",
      "Screaming Essence of Loathing",
      "Screaming Essence of Misery",
      "Screaming Essence of Rage",
      "Screaming Essence of Scorn",
      "Screaming Essence of Sorrow",
      "Screaming Essence of Spite",
      "Screaming Essence of Suffering",
      "Screaming Essence of Torment",
      "Screaming Essence of Woe",
      "Screaming Essence of Wrath",
      "Screaming Essence of Zeal",
      "Shrieking Essence of Anger",
      "Shrieking Essence of Anguish",
      "Shrieking Essence of Doubt",
      "Shrieking Essence of Fear",
      "Shrieking Essence of Hatred",
      "Shrieking Essence of Loathing",
      "Shrieking Essence of Misery",
      "Shrieking Essence of Suffering",
      "Shrieking Essence of Torment",
      "Wailing Essence of Anger",
      "Wailing Essence of Anguish",
      "Wailing Essence of Contempt",
      "Wailing Essence of Doubt",
      "Wailing Essence of Fear",
      "Wailing Essence of Greed",
      "Wailing Essence of Hatred",
      "Wailing Essence of Loathing",
      "Wailing Essence of Rage",
      "Wailing Essence of Sorrow",
      "Wailing Essence of Spite",
      "Wailing Essence of Suffering",
      "Wailing Essence of Torment",
      "Wailing Essence of Woe",
      "Wailing Essence of Wrath",
      "Wailing Essence of Zeal",
      "Weeping Essence of Anger",
      "Weeping Essence of Contempt",
      "Weeping Essence of Doubt",
      "Weeping Essence of Fear",
      "Weeping Essence of Greed",
      "Weeping Essence of Hatred",
      "Weeping Essence of Rage",
      "Weeping Essence of Sorrow",
      "Weeping Essence of Suffering",
      "Weeping Essence of Torment",
      "Weeping Essence of Woe",
      "Weeping Essence of Wrath",
      "Whispering Essence of Contempt",
      "Whispering Essence of Greed",
      "Whispering Essence of Hatred",
      "Whispering Essence of Woe",
      "Screaming Essence of Anguish",
    ],
    name: "Essences",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Ib3Jyb3IxIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/748d594bde/Horror1.png",
  },

  incubatorFilter: {
    items: [
      "Geomancer's Incubator",
      "Time-Lost Incubator",
      "Thaumaturge's Incubator",
      "Diviner's Incubator",
      "Ornate Incubator",
      "Foreboding Incubator",
      "Infused Incubator",
      "Fragmented Incubator",
      "Singular Incubator",
      "Celestial Jeweller's Incubator",
      "Enchanted Incubator",
      "Cartographer's Incubator",
      "Skittering Incubator",
      "Fossilised Incubator",
      "Abyssal Incubator",
      "Mysterious Incubator",
      "Celestial Armoursmith's Incubator",
      "Otherworldly Incubator",
      "Obscured Incubator",
      "Decadent Incubator",
      "Celestial Blacksmith's Incubator",
      "Morphing Incubator",
      "Maddening Incubator",
      "Blighted Incubator",
      "Primal Incubator",
    ],
    name: "Incubators",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdWJhdGlvbi9JbmN1YmF0aW9uQXJtb3VyIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/637c41a730/IncubationArmour.png",
  },

  blightedMapFilter: {
    items: [
      "Blighted Chateau Map",
      "Blighted Estuary Map",
      "Blighted Crimson Temple Map",
      "Blighted Fields Map",
      "Blighted Summit Map",
      "Blighted Alleyways Map",
      "Blighted Conservatory Map",
      "Blighted Basilica Map",
      "Blighted Promenade Map",
      "Blighted Underground Sea Map",
      "Blighted Bog Map",
      "Blighted Wharf Map",
      "Blighted Sepulchre Map",
      "Blighted Arcade Map",
      "Blighted Plateau Map",
      "Blighted Orchard Map",
      "Blighted Armoury Map",
      "Blighted Cemetery Map",
      "Blighted Primordial Blocks Map",
      "Blighted Wharf Map",
      "Blighted Promenade Map",
      "Blighted Desert Map",
      "Blighted Sulphur Vents Map",
      "Blighted Relic Chambers Map",
      "Blighted Spider Forest Map",
      "Blighted Vault Map",
      "Blighted Leyline Map",
      "Blighted Palace Map",
      "Blighted Park Map",
      "Blighted Arcade Map",
      "Blighted Port Map",
      "Blighted Racecourse Map",
      "Blighted Vault Map",
      "Blighted Lighthouse Map",
      "Blighted Mineral Pools Map",
      "Blighted Silo Map",
      "Blighted Dark Forest Map",
      "Blighted Shore Map",
      "Blighted Terrace Map",
      "Blighted Crimson Township Map",
      "Blighted Siege Map",
      "Blighted Barrows Map",
      "Blighted Crimson Temple Map",
      "Blighted Plaza Map",
      "Blighted Ghetto Map",
      "Blighted Underground Sea Map",
      "Blighted Spider Lair Map",
      "Blighted Conservatory Map",
      "Blighted Forking River Map",
      "Blighted Armoury Map",
      "Blighted Orchard Map",
      "Blighted Chateau Map",
      "Blighted Bog Map",
      "Blighted Arsenal Map",
      "Blighted Temple Map",
      "Blighted Foundry Map",
      "Blighted Pit Map",
      "Blighted Haunted Mansion Map",
      "Blighted Dig Map",
      "Blighted Mud Geyser Map",
      "Blighted Canyon Map",
      "Blighted Strand Map",
      "Blighted Wasteland Map",
      "Blighted Grave Trough Map",
      "Blighted Estuary Map",
      "Blighted Moon Temple Map",
      "Blighted Atoll Map",
      "Blighted Stagnation Map",
      "Blighted Tropical Island Map",
      "Blighted Arid Lake Map",
      "Blighted Defiled Cathedral Map",
      "Blighted Reef Map",
      "Blighted Thicket Map",
      "Blighted Dry Sea Map",
      "Blighted Ancient City Map",
      "Blighted Courtyard Map",
      "Blighted Lava Lake Map",
      "Blighted Ashen Wood Map",
      "Blighted Dunes Map",
      "Blighted Forbidden Woods Map",
      "Blighted Bog Map",
      "Blighted Basilica Map",
      "Blighted Silo Map",
      "Blighted Chateau Map",
      "Blighted Spider Forest Map",
      "Blighted Lighthouse Map",
      "Blighted Dry Sea Map",
      "Blighted Forbidden Woods Map",
      "Blighted Armoury Map",
      "Blighted Arcade Map",
      "Blighted Sepulchre Map",
      "Blighted Ghetto Map",
      "Blighted Cemetery Map",
      "Blighted Mineral Pools Map",
      "Blighted Forbidden Woods Map",
      "Blighted Conservatory Map",
      "Blighted Spider Lair Map",
      "Blighted Desert Map",
      "Blighted Strand Map",
      "Blighted Chateau Map",
      "Blighted Arid Lake Map",
      "Blighted Racecourse Map",
      "Blighted Moon Temple Map",
      "Blighted Dry Sea Map",
      "Blighted Courtyard Map",
      "Blighted Orchard Map",
      "Blighted Leyline Map",
      "Blighted Promenade Map",
      "Blighted Vault Map",
      "Blighted Atoll Map",
      "Blighted Estuary Map",
      "Blighted Barrows Map",
      "Blighted Spider Lair Map",
      "Blighted Palace Map",
      "Blighted Tropical Island Map",
      "Blighted Port Map",
      "Blighted Silo Map",
      "Blighted Ancient City Map",
      "Blighted Wharf Map",
      "Blighted Mud Geyser Map",
      "Blighted Crimson Township Map",
      "Blighted Plaza Map",
      "Blighted Cemetery Map",
      "Blighted Stagnation Map",
      "Blighted Dunes Map",
      "Blighted Reef Map",
      "Blighted Canyon Map",
      "Blighted Racecourse Map",
      "Blighted Leyline Map",
      "Blighted Foundry Map",
      "Blighted Wasteland Map",
      "Blighted Mineral Pools Map",
      "Blighted Relic Chambers Map",
      "Blighted Siege Map",
      "Blighted Ashen Wood Map",
      "Blighted Mud Geyser Map",
      "Blighted Ancient City Map",
      "Blighted Foundry Map",
      "Blighted Haunted Mansion Map",
      "Blighted Pit Map",
      "Blighted Spider Forest Map",
      "Blighted Grave Trough Map",
      "Blighted Wasteland Map",
      "Blighted Dark Forest Map",
      "Blighted Temple Map",
      "Blighted Grave Trough Map",
      "Blighted Promenade Map",
      "Blighted Tropical Island Map",
      "Blighted Crimson Township Map",
      "Blighted Ghetto Map",
      "Blighted Desert Map",
      "Blighted Dig Map",
      "Blighted Forking River Map",
      "Blighted Courtyard Map",
      "Blighted Lighthouse Map",
      "Blighted Silo Map",
      "Blighted Atoll Map",
      "Blighted Reef Map",
      "Blighted Canyon Map",
      "Blighted Leyline Map",
      "Blighted Strand Map",
      "Blighted Arid Lake Map",
      "Blighted Moon Temple Map",
      "Blighted Dig Map",
      "Blighted Vault Map",
      "Blighted Pit Map",
      "Blighted Plaza Map",
      "Blighted Barrows Map",
      "Blighted Dunes Map",
      "Blighted Wharf Map",
      "Blighted Relic Chambers Map",
      "Blighted Siege Map",
      "Blighted Estuary Map",
      "Blighted Orchard Map",
      "Blighted Port Map",
      "Blighted Forbidden Woods Map",
      "Blighted Spider Forest Map",
      "Blighted Atoll Map",
      "Blighted Leyline Map",
      "Blighted Lighthouse Map",
      "Blighted Spider Lair Map",
      "Blighted Stagnation Map",
      "Blighted Foundry Map",
      "Blighted Cemetery Map",
      "Blighted Mud Geyser Map",
      "Blighted Strand Map",
      "Blighted Chateau Map",
      "Blighted Courtyard Map",
      "Blighted Ancient City Map",
      "Blighted Desert Map",
      "Blighted Relic Chambers Map",
      "Blighted Port Map",
      "Blighted Ghetto Map",
      "Blighted Mineral Pools Map",
      "Blighted Dunes Map",
      "Blighted Promenade Map",
      "Blighted Siege Map",
      "Blighted Grave Trough Map",
      "Blighted Pit Map",
      "Blighted Racecourse Map",
      "Blighted Plaza Map",
      "Blighted Conservatory Map",
      "Blighted Arid Lake Map",
      "Blighted Reef Map",
      "Blighted Tropical Island Map",
      "Blighted Haunted Mansion Map",
      "Blighted Dry Sea Map",
      "Blighted Canyon Map",
      "Blighted Wasteland Map",
      "Blighted Port Map",
      "Blighted Plaza Map",
      "Blighted Strand Map",
      "Blighted Pit Map",
      "Blighted Racecourse Map",
      "Blighted Chateau Map",
      "Blighted Arid Lake Map",
      "Blighted Vault Map",
      "Blighted Ancient City Map",
      "Blighted Courtyard Map",
      "Blighted Dry Sea Map",
      "Blighted Spider Forest Map",
      "Blighted Atoll Map",
      "Blighted Wasteland Map",
      "Blighted Mud Geyser Map",
      "Blighted Ghetto Map",
      "Blighted Foundry Map",
      "Blighted Mineral Pools Map",
      "Blighted Wharf Map",
      "Blighted Orchard Map",
      "Blighted Lighthouse Map",
      "Blighted Silo Map",
      "Blighted Haunted Mansion Map",
      "Blighted Moon Temple Map",
      "Blighted Tropical Island Map",
      "Blighted Cemetery Map",
      "Blighted Spider Lair Map",
      "Blighted Barrows Map",
      "Blighted Forbidden Woods Map",
      "Blighted Estuary Map",
      "Blighted Dig Map",
      "Blighted Stagnation Map",
      "Blighted Pit Map",
      "Blighted Courtyard Map",
      "Blighted Ghetto Map",
      "Blighted Canyon Map",
      "Blighted Reef Map",
      "Blighted Stagnation Map",
      "Blighted Haunted Mansion Map",
      "Blighted Estuary Map",
      "Blighted Dunes Map",
    ],
    name: "Blighted Maps",
    icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9Gb3JraW5nUml2ZXIiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MSwibW4iOjExLCJtdCI6MTUsIm1iIjp0cnVlfV0/d14b4572d0/ForkingRiver.png",
  },
  deliriumOrbFilter: {
    items: [
      "Skittering Delirium Orb",
      "Cartographer's Delirium Orb",
      "Diviner's Delirium Orb",
      "Fossilised Delirium Orb",
      "Thaumaturge's Delirium Orb",
      "Fine Delirium Orb",
      "Amorphous Delirium Orb",
      "Obscured Delirium Orb",
      "Foreboding Delirium Orb",
      "Singular Delirium Orb",
      "Blighted Delirium Orb",
      "Timeless Delirium Orb",
      "Fragmented Delirium Orb",
      "Whispering Delirium Orb",
      "Imperial Delirium Orb",
      "Jeweller's Delirium Orb",
      "Abyssal Delirium Orb",
      "Armoursmith's Delirium Orb",
      "Blacksmith's Delirium Orb",
    ],
    name: "Delirium Orbs",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRGVsaXJpdW0vRGVsaXJpdW1PcmJTY2FyYWJzIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/fa4c5160ca/DeliriumOrbScarabs.png",
  },
  beastFilter: {
    items: [
      "Bleached Crawler",
      "Craicic Chimeral",
      "Farric Tiger Alpha",
      "Fenumal Plagued Arachnid",
      "Farrul, First of the Plains",
      "Parasite",
      "Fenumus, First of the Night",
      "Saqawine Rhex",
      "Craicic Maw",
      "Craiceann, First of the Deep",
      "Merveil's Favoured",
      "Fenumal Hybrid Arachnid",
      "Saqawal, First of the Sky",
      "Saqawine Cobra",
      "Farric Wolf Alpha",
      "Farric Lynx Alpha",
      "Rotting Vulture",
      "Saqawine Vulture",
      "Adolescent Rhex",
      "Craicic Spider Crab",
      "Avalanche Rider",
      "Craicic Vassal",
      "Escaped Rhex",
      "Pitbull Demon",
      "Infested Rhoa",
      "Spitting Parasite",
      "Craicic Savage Crab",
      "Farric Frost Hellion Alpha",
      "Craicic Watcher",
      "Merveil's Chosen",
      "Stygian Ape",
      "Freezing Wolf",
      "Hairy Bonecruncher",
      "Predatory Scorpion",
      "Brine Vassal",
      "Spindle Spider",
      "Leaping Spider",
      "Fenumal Queen",
      "Fenumal Devourer",
      "Farric Pit Hound",
      "Saqawine Blood Viper",
      "Fenumal Scrabbler",
      "Barb Serpent",
      "Savage Crab",
      "Purge Hound",
      "Murk Runner",
      "Vicious Parasite",
      "Forest Beast",
      "Shaggy Monstrosity",
      "Sewage Crawler",
      "Maternal Rhex",
      "Blood Chieftain",
      "Chrome-touched Chimeral",
      "Corrupted Rhoa",
      "Farric Ape",
      "Black Scorpion",
      "Enraptured Beast",
      "Bone Cruncher",
      "Cursed Spawn",
      "Farric Goliath",
      "Fenumal Scorpion",
      "Vaulting Croaker",
      "Sand Skitterer",
      "Mountain Hellion Alpha",
      "Fetid Maw",
      "Echo of the Verdant",
      "Alpine Shaman",
      "Bone Rhoa",
      "Elder-Blessed Rhoa",
      "Elder-Blessed Hellion",
      "Elder-Blessed Goatman",
      "Crypt Ambusher",
      "Elder-Blessed Cobra",
      "Lurking Venom",
      "Enraptured Crab",
      "Scum Crawler",
      "Farric Magma Hound",
      "Farric Flame Hellion Alpha",
      "Flame Hellion",
      "Avian Retch",
      "Dune Hellion",
      "Carrion Queen",
      "Porcupine Goliath",
      "Mountain Lynx",
      "Alpine Devil",
      "Mountain Hellion",
      "Rhoa Mare",
      "Mindless Scavenger",
      "Chimeric Croaker",
      "Carrion Swarmer",
      "Plummeting Ursa",
      "Chrome-touched Goliath",
      "Carrion Burrower",
      "Host Chieftain",
      "Corrupted Beast",
      "Cave Beast",
      "Carnage Ape",
      "Fury Hound",
      "Goatman Shaman",
      "Gravel Eater",
      "Plated Parasite",
      "Colossus Crusher",
      "Dust Scrabbler",
      "Grazing Taurus",
      "Gluttonous Gull",
      "Barrow Ape",
      "Scavenging Vulture",
      "Spine Serpent",
      "Merveil's Blessed",
      "Night Adder",
      "Glade Mamba",
      "Scalding Arachnid",
      "Bearded Devil",
      "Merveil's Attendant",
      "Arakaali's Daughter",
      "Plumed Chimeral",
      "Obsidian Eater",
      "Talon Archer",
      "Bramble Cobra",
      "Tercel Rhoa",
      "Chrome-touched Croaker",
      "Chrome-infused Croaker",
      "Hybrid Arachnid",
      "Carnage Chieftain",
      "Infested Crab",
      "Dread Primate",
      "Blood Ape",
      "Singing Siren",
      "Snow Wolf",
      "Ink Spinner",
      "Infested Tunnelfiend",
      "Goatman",
      "Bearded Shaman",
      "Chrome-infused Chimeral",
      "Cave Skitterer",
      "Venomous Spawn",
      "Webbed Spider",
      "Virulent Spider",
      "Enraptured Arachnid",
      "Corrupted Arach",
      "Crustacean Sniper",
      "Infested Ape",
      "Merveil's Retainer",
      "Host Cobra",
      "Sulphuric Scorpion",
      "Soulless Watcher",
      "Rooster Fiend",
      "Bearded Skycaller",
      "Infested Skitterer",
      "Goatman Fire-raiser",
      "Acid Slitherer",
      "Host Adder",
      "Skeletal Beast",
      "Farric Taurus",
      "Fenumal Widow",
      "Sand Leaper",
      "Chrome-infused Goliath",
      "Granite Eater",
      "Plagued Arachnid",
      "Noxious Tarantula",
      "Rock Spitter",
      "Ruins Hellion",
      "Mutant Arach",
      "Craicic Sand Spitter",
      "Farric Chieftain",
      "Infested Maw",
      "Hill Devil",
      "Devourer",
      "Shackled Hellion",
      "Fighting Bull",
      "Saqawine Rhoa",
      "Saqawine Chimeral",
      "Enslaved Hellion",
      "Dirt Scrabbler",
      "Craicic Squid",
      "Farric Ursa",
      "Saqawine Retch",
      "Craicic Shield Crab",
      "Farric Gargantuan",
      "Farric Goatman",
    ],
    name: "Beasts",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQmVzdGlhcnlPcmJGdWxsIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/3214b44360/BestiaryOrbFull.png",
  },
  resonatorFilter: {
    items: [
      "Prime Chaotic Resonator",
      "Prime Alchemical Resonator",
      "Powerful Chaotic Resonator",
      "Powerful Alchemical Resonator",
      "Potent Alchemical Resonator",
      "Potent Chaotic Resonator",
      "Primitive Chaotic Resonator",
      "Primitive Alchemical Resonator",
    ],
    name: "Resonators",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRGVsdmUvUmVyb2xsMngyQyIsInciOjIsImgiOjIsInNjYWxlIjoxfV0/584267701b/Reroll2x2C.png",
  },
  prophecyFilter: {
    items: [
      "Trash to Treasure",
      "The Queen's Sacrifice",
      "Fated Connections",
      "Monstrous Treasure",
      "Darktongue's Shriek",
      "The Forgotten Soldiers",
      "The Unbreathing Queen V",
      "Unbearable Whispers V",
      "The Plaguemaw V",
      "Storm on the Reef",
      "Song of the Sekhema",
      "Unbearable Whispers IV",
      "The Feral Lord V",
      "The Unbreathing Queen IV",
      "Anarchy's End IV",
      "Thaumaturgical History III",
      "Pools of Wealth",
      "Deadly Rivalry V",
      "Beyond Sight IV",
      "Thaumaturgical History IV",
      "Against the Tide",
      "Day of Sacrifice IV",
      "A Dishonourable Death",
      "Unbearable Whispers III",
      "The Bowstring's Music",
      "Vaal Winds",
      "The Feral Lord IV",
      "The Great Leader of the North",
      "The Unbreathing Queen III",
      "A Prodigious Hand",
      "Cleanser of Sins",
      "The Mentor",
      "Cold Blooded Fury",
      "Deadly Rivalry IV",
      "Bountiful Traps",
      "Fire, Wood and Stone",
      "The Jeweller's Touch",
      "The Plaguemaw III",
      "The Plaguemaw IV",
      "The Warmongers IV",
      "Twice Enchanted",
      "Battle Hardened",
      "Anarchy's End III",
      "The Child of Lunaris",
      "The King's Path",
      "The Great Mind of the North",
      "A Master Seeks Help",
      "The Ambitious Bandit III",
      "Blood of the Betrayed",
      "Weeping Death",
      "Path of Betrayal",
      "Wind and Thunder",
      "Roth's Legacy",
      "A Whispered Prayer",
      "Deadly Rivalry III",
      "Plague of Frogs",
      "Storm on the Horizon",
      "The Feral Lord III",
      "The Warmongers II",
      "The Warmongers III",
      "The Watcher's Watcher",
      "Last of the Wildmen",
      "A Vision of Ice and Fire",
      "The Forgotten Garrison",
      "Visions of the Drowned",
      "In the Grasp of Corruption",
      "Anarchy's End II",
      "Deadly Rivalry II",
      "Vaal Invasion",
      "Lost in the Pages",
      "Beyond Sight III",
      "Day of Sacrifice III",
      "Defiled in the Sceptre",
      "Fire and Ice",
      "Ancient Doom",
      "Crushing Squall",
      "Erasmus' Gift",
      "Fire from the Sky",
      "Holding the Bridge",
      "Ice from Above",
      "Nature's Resilience",
      "Severed Limbs",
      "The Apex Predator",
      "The Feral Lord II",
      "The Nest",
      "The Servant's Heart",
      "The Soulless Beast",
      "The Twins",
      "The Unbreathing Queen II",
      "Unbearable Whispers II",
      "A Master Seeks Help",
      "A Master Seeks Help",
      "The Dream Trial",
      "The Hollow Pledge",
      "Abnormal Effulgence",
      "Unnatural Energy",
      "Fear's Wide Reach",
      "Deadly Twins",
      "The Plaguemaw II",
      "From Death Springs Life",
      "The Last Watch",
      "Kalandra's Craft",
      "Thaumaturgical History II",
      "The Bishop's Legacy",
      "A Firm Foothold",
      "A Forest of False Idols",
      "A Regal Death",
      "A Valuable Combination",
      "Anarchy's End I",
      "Beyond Sight I",
      "Beyond Sight II",
      "Custodians of Silence",
      "Day of Sacrifice I",
      "Day of Sacrifice II",
      "Deadly Rivalry I",
      "Dying Cry",
      "Ending the Torment",
      "Erased from Memory",
      "Fire and Brimstone",
      "Flesh of the Beast",
      "From The Void",
      "Golden Touch",
      "Graceful Flames",
      "Heart of the Fire",
      "Heavy Blows",
      "Hidden Vaal Pathways",
      "Lasting Impressions",
      "Lightning Falls",
      "Living Fires",
      "Mouth of Horrors",
      "Mysterious Invaders",
      "Nemesis of Greed",
      "Overflowing Riches",
      "Plague of Rats",
      "Pleasure and Pain",
      "Power Magnified",
      "Rebirth",
      "Reforged Bonds",
      "Risen Blood",
      "Smothering Tendrils",
      "Soil, Worms and Blood",
      "Thaumaturgical History I",
      "The Alchemist",
      "The Ambitious Bandit I",
      "The Ambitious Bandit II",
      "The Beautiful Guide",
      "The Beginning and the End",
      "The Bloody Flowers Redux",
      "The Brutal Enforcer",
      "The Corrupt",
      "The Dreamer's Dream",
      "The Eagle's Cry",
      "The Feral Lord I",
      "The Flayed Man",
      "The Flow of Energy",
      "The Fortune Teller's Collection",
      "The Four Feral Exiles",
      "The Hardened Armour",
      "The Hungering Swarm",
      "The Invader",
      "The Karui Rebellion",
      "The King and the Brambles",
      "The Lady in Black",
      "The Lost Maps",
      "The Lost Undying",
      "The Misunderstood Queen",
      "The Mysterious Gift",
      "The Petrified",
      "The Plaguemaw I",
      "The Prison Key",
      "The Queen's Vaults",
      "The Scout",
      "The Sharpened Blade",
      "The Silverwood",
      "The Singular Spirit",
      "The Sinner's Stone",
      "The Snuffed Flame",
      "The Stockkeeper",
      "The Sword King's Passion",
      "The Unbreathing Queen I",
      "The Undead Brutes",
      "The Undead Storm",
      "The Vanguard",
      "The Walking Mountain",
      "The Ward's Ward",
      "The Warmongers I",
      "The Wealthy Exile",
      "Touched by the Wind",
      "Unbearable Whispers I",
      "Vital Transformation",
      "Waiting in Ambush",
      "Winter's Mournful Melodies",
      "Greed's Folly",
      "Agony at Dusk",
      "Dark Instincts",
      "Dance of Steel",
      "The Dreaded Rhoa",
      "Burning Dread",
      "The Storm Spire",
      "Black Devotion",
      "Trapped in the Tower",
      "End of the Light",
      "A Rift in Time",
      "Sun's Punishment",
      "Cold Greed",
      "The Malevolent Witch",
      "The Nightmare Awakens",
      "The Fall of an Empire",
      "Blind Faith",
      "Crimson Hues",
      "Blinding Light",
      "Faith Exhumed",
      "A Master Seeks Help",
      "A Master Seeks Help",
      "Strong as a Bull",
      "A Call into the Void",
      "The God of Misfortune",
      "Gilded Within",
      "Hidden Reinforcements",
      "Notched Flesh",
      "Forceful Exorcism",
      "The Trembling Earth",
      "Hunter's Lesson",
      "Blood in the Eyes",
      "An Unseen Peril",
      "The Brothers of Necromancy",
      "Resistant to Change",
      "Possessed Foe",
      "Baptism by Death",
      "The Prison Guard",
      "The Cursed Choir",
    ],
    name: "Prophecies",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUHJvcGhlY3lPcmJSZWQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/c45e04700d/ProphecyOrbRed.png",
  },

  divinationFilter: {
    items: [
      "House of Mirrors",
      "The Doctor",
      "The Demon",
      "The Fiend",
      "Unrequited Love",
      "Brother's Stash",
      "Beauty Through Death",
      "The Nurse",
      "The Cheater",
      "Alluring Bounty",
      "The Immortal",
      "Succor of the Sinless",
      "The Scout",
      "The Dragon's Heart",
      "Love Through Ice",
      "Wealth and Power",
      "Gift of Asenath",
      "Abandoned Wealth",
      "Pride of the First Ones",
      "Desecrated Virtue",
      "The Scout",
      "Seven Years Bad Luck",
      "Immortal Resolve",
      "The Samurai's Eye",
      "Deadly Joy",
      "Nook's Crown",
      "The Enlightened",
      "The Price of Loyalty",
      "The Iron Bard",
      "A Note in the Wind",
      "The Astromancer",
      "Eternal Bonds",
      "The Greatest Intentions",
      "The White Knight",
      "The Strategist",
      "The Offspring",
      "The Progeny of Lunaris",
      "Keeper's Corruption",
      "The Saint's Treasure",
      "The Patient",
      "The Academic",
      "The Spark and the Flame",
      "The Artist",
      "The Long Con",
      "Hunter's Reward",
      "The Damned",
      "Desperate Crusade",
      "The Eye of Terror",
      "Council of Cats",
      "The Celestial Justicar",
      "The Sacrifice",
      "The Eternal War",
      "Winter's Embrace",
      "The Polymath",
      "Burning Blood",
      "Dark Dreams",
      "Azyran's Reward",
      "Peaceful Moments",
      "The Offering",
      "The Bones",
      "The Bitter Blossom",
      "Luminous Trove",
      "Broken Promises",
      "The Sustenance",
      "The Hoarder",
      "The Bargain",
      "The Gulf",
      "The Queen",
      "The World Eater",
      "The Escape",
      "Draped in Dreams",
      "Ambitious Obsession",
      "The Aspirant",
      "The Sephirot",
      "The Life Thief",
      "Dementophobia",
      "The Rabbit's Foot",
      "Chaotic Disposition",
      "The Ethereal",
      "The Celestial Stone",
      "The Endless Darkness",
      "The Eldritch Decay",
      "A Stone Perfected",
      "The Chosen",
      "Mawr Blaidd",
      "The Soul",
      "The Porcupine",
      "The Professor",
      "The Innocent",
      "The Landing",
      "The Primordial",
      "Void of the Elements",
      "Remembrance",
      "The Craving",
      "Underground Forest",
      "A Familiar Call",
      "Brotherhood in Exile",
      "The Shortcut",
      "The Enthusiasts",
      "A Modest Request",
      "Lachrymal Necrosis",
      "Terrible Secret of Space",
      "Chasing Risk",
      "Dying Light",
      "Pride Before the Fall",
      "Bowyer's Dream",
      "Emperor of Purity",
      "Lucky Deck",
      "The Brittle Emperor",
      "The Dapper Prodigy",
      "The Hunger",
      "The Pact",
      "The Thaumaturgist",
      "The Vast",
      "Rebirth",
      "The Breach",
      "The Jeweller's Boon",
      "Perfection",
      "The Undisputed",
      "Boon of the First Ones",
      "The Seeker",
      "The Deep Ones",
      "The Heroic Shot",
      "Divine Justice",
      "Deathly Designs",
      "Etched in Blood",
      "The Fishmonger",
      "Prometheus' Armoury",
      "The Awakened",
      "The Hive of Knowledge",
      "The Whiteout",
      "Fateful Meeting",
      "Brush, Paint and Palette",
      "The Mind's Eyes",
      "The Price of Prescience",
      "The Emptiness",
      "The Forgotten Treasure",
      "The Catch",
      "The Hale Heart",
      "The Scavenger",
      "The Old Man",
      "The King's Heart",
      "Vinia's Token",
      "A Mother's Parting Gift",
      "Anarchy's Price",
      "Assassin's Favour",
      "Audacity",
      "Blind Venture",
      "Boundless Realms",
      "Cartographer's Delight",
      "Coveted Possession",
      "Death",
      "Destined to Crumble",
      "Dialla's Subjugation",
      "Doedre's Madness",
      "Dying Anguish",
      "Earth Drinker",
      "Emperor's Luck",
      "Gemcutter's Promise",
      "Gift of the Gemling Queen",
      "Glimmer of Hope",
      "Grave Knowledge",
      "Her Mask",
      "Heterochromia",
      "Hope",
      "Hubris",
      "Humility",
      "Hunter's Resolve",
      "Jack in the Box",
      "Lantador's Lost Love",
      "Last Hope",
      "Light and Truth",
      "Lost Worlds",
      "Loyalty",
      "Lucky Connections",
      "Lysah's Respite",
      "Merciless Armament",
      "Prosperity",
      "Rain Tempter",
      "Rats",
      "Scholar of the Seas",
      "Shard of Fate",
      "The Aesthete",
      "The Arena Champion",
      "The Avenger",
      "The Battle Born",
      "The Betrayal",
      "The Body",
      "The Calling",
      "The Cartographer",
      "The Cataclysm",
      "The Catalyst",
      "The Chains that Bind",
      "The Conduit",
      "The Cursed King",
      "The Dark Mage",
      "The Demoness",
      "The Doppelganger",
      "The Dragon",
      "The Drunken Aristocrat",
      "The Encroaching Darkness",
      "The Endurance",
      "The Explorer",
      "The Feast",
      "The Fletcher",
      "The Flora's Gift",
      "The Formless Sea",
      "The Fox",
      "The Gemcutter",
      "The Gentleman",
      "The Gladiator",
      "The Harvester",
      "The Incantation",
      "The Inoculated",
      "The Inventor",
      "The Jester",
      "The King's Blade",
      "The Last One Standing",
      "The Lich",
      "The Lion",
      "The Lord in Black",
      "The Lover",
      "The Lunaris Priestess",
      "The Mercenary",
      "The Metalsmith's Gift",
      "The Oath",
      "The One With All",
      "The Pack Leader",
      "The Penitent",
      "The Poet",
      "The Rabid Rhoa",
      "The Risk",
      "The Road to Power",
      "The Scarred Meadow",
      "The Scholar",
      "The Sigil",
      "The Siren",
      "The Spoiled Prince",
      "The Stormcaller",
      "The Summoner",
      "The Sun",
      "The Surgeon",
      "The Surveyor",
      "The Survivalist",
      "The Throne",
      "The Tower",
      "The Traitor",
      "The Trial",
      "The Twins",
      "The Tyrant",
      "The Union",
      "The Valkyrie",
      "The Visionary",
      "The Void",
      "The Warden",
      "The Warlord",
      "The Watcher",
      "The Web",
      "The Wind",
      "The Wolf",
      "The Wolf's Shadow",
      "The Wrath",
      "Three Faces in the Dark",
      "Thunderous Skies",
      "Time-Lost Relic",
      "Tranquillity",
      "Treasure Hunter",
      "Turn the Other Cheek",
      "Volatile Power",
      "Mitts",
      "The Valley of Steel Boxes",
      "Call to the First Ones",
      "The Wretched",
      "Lingering Remnants",
      "The Coming Storm",
      "The Wolven King's Bite",
      "The Wolverine",
      "The Garish Power",
      "The Standoff",
      "The Forsaken",
      "Might is Right",
      "Atziri's Arsenal",
      "The Opulent",
      "The Blazing Fire",
      "The Ruthless Ceinture",
      "No Traces",
      "The Eye of the Dragon",
      "The Realm",
      "Left to Fate",
      "The Obscured",
      "The Deceiver",
      "The Puzzle",
      "The Insatiable",
      "Forbidden Power",
      "The Dreamer",
      "Three Voices",
      "The Army of Blood",
      "The Beast",
      "The Sword King's Salute",
      "The Master",
      "The Fathomless Depths",
      "The Rite of Elements",
      "The Dreamland",
      "The Admirer",
      "The Undaunted",
      "The Witch",
      "The Darkest Dream",
      "Harmony of Souls",
      "The Twilight Moon",
      "The Wilted Rose",
      "The Price of Protection",
      "The Cacophony",
      "A Dab of Ink",
      "Sambodhi's Vow",
      "Arrogance of the Vaal",
      "The Mad King",
      "Alone in the Darkness",
      "The Lord of Celebration",
      "Dark Temptation",
      "The Journey",
      "The Messenger",
      "Monochrome",
      "The Golden Era",
      "Boon of Justice",
      "Vanity",
      "Thirst for Knowledge",
      "Imperial Legacy",
      "Echoes of Love",
      "The Fool",
      "Demigod's Wager",
      "Buried Treasure",
      "The Archmage's Right Hand",
      "Vile Power",
      "The Mountain",
      "The Skeleton",
      "Akil's Prophecy",
      "The Wolf's Legacy",
      "The Deal",
      "The Side Quest",
      "More is Never Enough",
      "Cameria's Cut",
      "Friendship",
      "Baited Expectations",
      "The Tinkerer's Table",
      "The Easy Stroll",
      "The Tumbleweed",
      "The Unexpected Prize",
      "Triskaidekaphobia",
      "The Journalist",
      "Unchained",
      "The Cache",
      "Cursed Words",
      "Society's Remorse",
      "The Bear Woman",
      "The Long Watch",
      "Acclimatisation",
      "Haunting Shadows",
      "Reckless Ambition",
      "The Hook",
      "Prejudice",
      "The Adventuring Spirit",
      "The Card Sharp",
      "Sambodhi's Wisdom",
      "The Last Supper",
      "A Sea of Blue",
      "Costly Curio",
      "The Blessing of Moosh",
      "The Fox in the Brambles",
      "Guardian's Challenge",
      "Disdain",
      "The Prince of Darkness",
      "Rain of Chaos",
      "The Master Artisan",
      "The Carrion Crow",
      "The Gambler",
      "The Hermit",
      "Struck by Lightning",
    ],
    name: "Divination Cards",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvRGl2aW5hdGlvbi9JbnZlbnRvcnlJY29uIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/f34bf8cbb5/InventoryIcon.png",
  },
};
