export const itemFilter = {
  fragments: [
    {
      name: "Harvest Lifeforce",
      items: [
        "Wild Crystallised Lifeforce",
        "Sacred Crystallised Lifeforce",
        "Primal Crystallised Lifeforce",
        "Vivid Crystallised Lifeforce",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSGFydmVzdC9QcmltYWxMaWZlZm9yY2UiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/d5d53c61c3/PrimalLifeforce.png",
    },
    {
      name: "Gilded Scarabs",
      items: [
        "Gilded Divination Scarab",
        "Gilded Reliquary Scarab",
        "Gilded Harbinger Scarab",
        "Gilded Ambush Scarab",
        "Gilded Breach Scarab",
        "Gilded Abyss Scarab",
        "Gilded Expedition Scarab",
        "Gilded Legion Scarab",
        "Gilded Bestiary Scarab",
        "Gilded Blight Scarab",
        "Gilded Cartography Scarab",
        "Gilded Sulphite Scarab",
        "Gilded Metamorph Scarab",
        "Gilded Torment Scarab",
        "Gilded Shaper Scarab",
        "Gilded Elder Scarab",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9HcmVhdGVyU2NhcmFiRGl2aW5hdGlvbiIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/8101d1a6e1/GreaterScarabDivination.png",
    },
    {
      name: "Winged Scarabs",
      items: [
        "Winged Divination Scarab",
        "Winged Reliquary Scarab",
        "Winged Harbinger Scarab",
        "Winged Ambush Scarab",
        "Winged Breach Scarab",
        "Winged Abyss Scarab",
        "Winged Expedition Scarab",
        "Winged Legion Scarab",
        "Winged Bestiary Scarab",
        "Winged Blight Scarab",
        "Winged Cartography Scarab",
        "Winged Sulphite Scarab",
        "Winged Metamorph Scarab",
        "Winged Torment Scarab",
        "Winged Shaper Scarab",
        "Winged Elder Scarab",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9UaWVyNFNjYXJhYkRpdmluYXRpb24iLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/e6539f578d/Tier4ScarabDivination.png",
    },
    {
      name: "Shrieking Essences",
      items: [
        "Shrieking Essence of Contempt",
        "Shrieking Essence of Greed",
        "Shrieking Essence of Wrath",
        "Shrieking Essence of Zeal",
        "Shrieking Essence of Dread",
        "Shrieking Essence of Envy",
        "Shrieking Essence of Hatred",
        "Shrieking Essence of Loathing",
        "Shrieking Essence of Rage",
        "Shrieking Essence of Scorn",
        "Shrieking Essence of Sorrow",
        "Shrieking Essence of Spite",
        "Shrieking Essence of Anger",
        "Shrieking Essence of Fear",
        "Shrieking Essence of Woe",
        "Shrieking Essence of Anguish",
        "Shrieking Essence of Doubt",
        "Shrieking Essence of Misery",
        "Shrieking Essence of Suffering",
        "Shrieking Essence of Torment",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Db250ZW1wdDYiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/332e9b32e9/Contempt6.png",
    },
    {
      name: "Deafening Essences",
      items: [
        "Deafening Essence of Contempt",
        "Deafening Essence of Greed",
        "Deafening Essence of Wrath",
        "Deafening Essence of Zeal",
        "Deafening Essence of Dread",
        "Deafening Essence of Envy",
        "Deafening Essence of Hatred",
        "Deafening Essence of Loathing",
        "Deafening Essence of Rage",
        "Deafening Essence of Scorn",
        "Deafening Essence of Sorrow",
        "Deafening Essence of Spite",
        "Deafening Essence of Anger",
        "Deafening Essence of Fear",
        "Deafening Essence of Woe",
        "Deafening Essence of Anguish",
        "Deafening Essence of Doubt",
        "Deafening Essence of Misery",
        "Deafening Essence of Suffering",
        "Deafening Essence of Torment",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Db250ZW1wdDciLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/eabee1b2e2/Contempt7.png",
    },
    {
      name: "Breachstones",
      items: [
        "Uul-Netol's Flawless Breachstone",
        "Xoph's Flawless Breachstone",
        "Tul's Flawless Breachstone",
        "Esh's Flawless Breachstone",
        "Chayula's Pure Breachstone",
        "Chayula's Breachstone",
        "Chayula's Charged Breachstone",
        "Chayula's Enriched Breachstone",
        "Uul-Netol's Pure Breachstone",
        "Uul-Netol's Enriched Breachstone",
        "Esh's Pure Breachstone",
        "Tul's Pure Breachstone",
        "Uul-Netol's Charged Breachstone",
        "Xoph's Pure Breachstone",
        "Uul-Netol's Breachstone",
        "Xoph's Enriched Breachstone",
        "Tul's Enriched Breachstone",
        "Esh's Enriched Breachstone",
        "Xoph's Charged Breachstone",
        "Tul's Charged Breachstone",
        "Esh's Charged Breachstone",
        "Esh's Breachstone",
        "Xoph's Breachstone",
        "Tul's Breachstone",
        "Chayula's Flawless Breachstone",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaEZyYWdtZW50c0NoYW9zIiwic2NhbGUiOjF9XQ/4c99b7dd49/BreachFragmentsChaos.png",
    },
    {
      name: "Emblems",
      items: [
        "Timeless Maraketh Emblem",
        "Timeless Templar Emblem",
        "Unrelenting Timeless Karui Emblem",
        "Timeless Vaal Emblem",
        "Timeless Karui Emblem",
        "Unrelenting Timeless Maraketh Emblem",
        "Unrelenting Timeless Eternal Emblem",
        "Unrelenting Timeless Templar Emblem",
        "Unrelenting Timeless Vaal Emblem",
        "Timeless Eternal Emblem",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9NYXJha2V0aEZyYWdtZW50Iiwic2NhbGUiOjF9XQ/a81c4968ab/MarakethFragment.png",
    },
    {
      name: "Atziri",
      items: [
        "Sacrifice at Midnight",
        "Sacrifice at Noon",
        "Sacrifice at Dawn",
        "Sacrifice at Dusk",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9WYWFsQ29tcGxldGUiLCJzY2FsZSI6MX1d/63035d86d7/VaalComplete.png",
    },
    {
      name: "Uber Atziri",
      items: ["Mortal Rage", "Mortal Ignorance", "Mortal Hope", "Mortal Grief"],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9VYmVyVmFhbENvbXBsZXRlIiwic2NhbGUiOjF9XQ/994d9e2821/UberVaalComplete.png",
    },
    {
      name: "Elder",
      items: [
        "Fragment of Enslavement",
        "Fragment of Eradication",
        "Fragment of Constriction",
        "Fragment of Purification",
        "Fragment of Terror",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9FbGRlckNvbXBsZXRlIiwic2NhbGUiOjF9XQ/6db44597fe/ElderComplete.png",
    },
    {
      name: "Shaper",
      items: [
        "Fragment of the Hydra",
        "Fragment of the Phoenix",
        "Fragment of the Minotaur",
        "Fragment of the Chimera",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9TaGFwZXJDb21wbGV0ZSIsInNjYWxlIjoxfV0/ace686004d/ShaperComplete.png",
    },
    {
      name: "Uber Elder",
      items: [
        "Fragment of Knowledge",
        "Fragment of Shape",
        "Fragment of Terror",
        "Fragment of Emptiness",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9VYmVyRWxkZXJDb21wbGV0ZSIsInNjYWxlIjoxfV0/715e041869/UberElderComplete.png",
    },
    {
      name: "Crest of the Elderslayers",
      items: [
        "Drox's Crest",
        "Veritania's Crest",
        "Baran's Crest",
        "Al-Hezmin's Crest",
      ],
      icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9TaXJ1c0ZyYWdtZW50Q29tcGxldGUiLCJzY2FsZSI6MX1d/c585a0ae79/SirusFragmentComplete.png",
    },
  ],
  sextantFilter: {
    items: ["Sextant"],
    name: "Compass",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ2hhcmdlZENvbXBhc3MiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/ea8fcc3e35/ChargedCompass.png",
  },
  contractFilter: {
    items: [
      "Contract Agility 81+",
      "Contract Brute Force 81+",
      "Contract Counter-Thaumaturgy 81+",
      "Contract Deception 81+",
      "Contract Demolition 81+",
      "Contract Engineering 81+",
      "Contract Lockpicking 81+",
      "Contract Perception 81+",
      "Contract Trap Disarmament 81+",

      "Contract Agility",
      "Contract Brute Force",
      "Contract Counter-Thaumaturgy",
      "Contract Deception",
      "Contract Demolition",
      "Contract Engineering",
      "Contract Lockpicking",
      "Contract Perception",
      "Contract Trap Disarmament",
    ],
    name: "Contract ",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSGVpc3QvQ29udHJhY3RJdGVtMiIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/f755c71433/ContractItem2.png",
  },
  currencyFilter: {
    items: [
      "Abrasive Catalyst",
      "Accelerating Catalyst",
      "Ancient Orb",
      "Annulment Shard",
      "Armourer's Scrap",
      "Awakened Sextant",
      "Awakener's Orb",
      "Blacksmith's Whetstone",
      "Blessed Orb",
      "Blessing of Chayula",
      "Blessing of Esh",
      "Blessing of Tul",
      "Blessing of Uul-Netol",
      "Blessing of Xoph",
      "Blighted Scouting Report",
      "Cartographer's Chisel",
      "Charged Compass",
      "Chromatic Orb",
      "Comprehensive Scouting Report",
      "Crusader's Exalted Orb",
      "Delirious Scouting Report",
      "Divine Orb",
      "Eldritch Chaos Orb",
      "Eldritch Exalted Orb",
      "Eldritch Orb of Annulment",
      "Elevated Sextant",
      "Engineer's Orb",
      "Enkindling Orb",
      "Exalted Orb",
      "Exalted Shard",
      "Exceptional Eldritch Ember",
      "Exceptional Eldritch Ichor",
      "Explorer's Scouting Report",
      "Fertile Catalyst",
      "Gemcutter's Prism",
      "Glassblower's Bauble",
      "Grand Eldritch Ember",
      "Grand Eldritch Ichor",
      "Greater Eldritch Ember",
      "Greater Eldritch Ichor",
      "Harbinger's Orb",
      "Hunter's Exalted Orb",
      "Imbued Catalyst",
      "Influenced Scouting Report",
      "Instilling Orb",
      "Intrinsic Catalyst",
      "Jeweller's Orb",
      "Lesser Eldritch Ember",
      "Lesser Eldritch Ichor",
      "Maven's Orb",
      "Mirror Shard",
      "Mirror of Kalandra",
      "Noxious Catalyst",
      "Oil Extractor",
      "Operative's Scouting Report",
      "Orb of Alchemy",
      "Orb of Alteration",
      "Orb of Annulment",
      "Orb of Augmentation",
      "Orb of Binding",
      "Orb of Chance",
      "Orb of Conflict",
      "Orb of Dominance",
      "Orb of Fusing",
      "Orb of Horizons",
      "Orb of Regret",
      "Orb of Scouring",
      "Orb of Transmutation",
      "Orb of Unmaking",
      "Otherworldly Scouting Report",
      "Portal Scroll",
      "Primal Crystallised Lifeforce",
      "Prime Regrading Lens",
      "Prime Sextant",
      "Prismatic Catalyst",
      "Redeemer's Exalted Orb",
      "Regal Orb",
      "Ritual Vessel",
      "Sacred Crystallised Lifeforce",
      "Sacred Orb",
      "Scroll of Wisdom",
      "Secondary Regrading Lens",
      "Singular Scouting Report",
      "Stacked Deck",
      "Surveyor's Compass",
      "Tailoring Orb",
      "Tainted Armourer's Scrap",
      "Tainted Blacksmith's Whetstone",
      "Tainted Blessing",
      "Tainted Chaos Orb",
      "Tainted Chromatic Orb",
      "Tainted Divine Teardrop",
      "Tainted Exalted Orb",
      "Tainted Jeweller's Orb",
      "Tainted Mythic Orb",
      "Tainted Orb of Fusing",
      "Tempering Catalyst",
      "Tempering Orb",
      "Turbulent Catalyst",
      "Unstable Catalyst",
      "Vaal Orb",
      "Vaal Scouting Report",
      "Veiled Chaos Orb",
      "Vivid Crystallised Lifeforce",
      "Warlord's Exalted Orb",
      "Wild Crystallised Lifeforce",
    ],
    name: "Currencies",
    icon: "https://web.poecdn.com/image/Art/2DItems/Currency/CurrencyRerollRare.png?scale=1&w=1&h=1",
  },
  fragmentFilter: {
    items: [
      "Al-Hezmin's Crest",
      "Alva's Memory",
      "Baran's Crest",
      "Chayula's Breachstone",
      "Chayula's Charged Breachstone",
      "Chayula's Enriched Breachstone",
      "Chayula's Flawless Breachstone",
      "Chayula's Pure Breachstone",
      "Crescent Splinter",
      "Dedication to the Goddess",
      "Divine Vessel",
      "Drox's Crest",
      "Einhar's Memory",
      "Esh's Breachstone",
      "Esh's Charged Breachstone",
      "Esh's Enriched Breachstone",
      "Esh's Flawless Breachstone",
      "Esh's Pure Breachstone",
      "Fragment of Constriction",
      "Fragment of Emptiness",
      "Fragment of Enslavement",
      "Fragment of Eradication",
      "Fragment of Knowledge",
      "Fragment of Purification",
      "Fragment of Shape",
      "Fragment of Terror",
      "Fragment of the Chimera",
      "Fragment of the Hydra",
      "Fragment of the Minotaur",
      "Fragment of the Phoenix",
      "Gift to the Goddess",
      "Ignominious Fate",
      "Kirac's Memory",
      "Mortal Grief",
      "Mortal Hope",
      "Mortal Ignorance",
      "Mortal Rage",
      "Niko's Memory",
      "Offering to the Goddess",
      "Sacrifice at Dawn",
      "Sacrifice at Dusk",
      "Sacrifice at Midnight",
      "Sacrifice at Noon",
      "Simulacrum Splinter",
      "Simulacrum",
      "Splinter of Chayula",
      "Splinter of Esh",
      "Splinter of Tul",
      "Splinter of Uul-Netol",
      "Splinter of Xoph",
      "The Maven's Writ",
      "Timeless Eternal Emblem",
      "Timeless Eternal Empire Splinter",
      "Timeless Karui Emblem",
      "Timeless Karui Splinter",
      "Timeless Maraketh Emblem",
      "Timeless Maraketh Splinter",
      "Timeless Templar Emblem",
      "Timeless Templar Splinter",
      "Timeless Vaal Emblem",
      "Timeless Vaal Splinter",
      "Tribute to the Goddess",
      "Tul's Breachstone",
      "Tul's Charged Breachstone",
      "Tul's Enriched Breachstone",
      "Tul's Flawless Breachstone",
      "Tul's Pure Breachstone",
      "Unrelenting Timeless Eternal Emblem",
      "Unrelenting Timeless Karui Emblem",
      "Unrelenting Timeless Maraketh Emblem",
      "Unrelenting Timeless Templar Emblem",
      "Unrelenting Timeless Vaal Emblem",
      "Uul-Netol's Breachstone",
      "Uul-Netol's Charged Breachstone",
      "Uul-Netol's Enriched Breachstone",
      "Uul-Netol's Flawless Breachstone",
      "Uul-Netol's Pure Breachstone",
      "Veritania's Crest",
      "Victorious Fate",
      "Will of Chaos",
      "Xoph's Breachstone",
      "Xoph's Charged Breachstone",
      "Xoph's Enriched Breachstone",
      "Xoph's Flawless Breachstone",
      "Xoph's Pure Breachstone",
    ],
    name: "Fragments",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaEZyYWdtZW50c0NoYW9zIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/04b5c032f4/BreachFragmentsChaos.png",
  },
  oilFilter: {
    items: [
      "Amber Oil",
      "Azure Oil",
      "Black Oil",
      "Clear Oil",
      "Crimson Oil",
      "Golden Oil",
      "Indigo Oil",
      "Opalescent Oil",
      "Reflective Oil",
      "Sepia Oil",
      "Silver Oil",
      "Tainted Oil",
      "Teal Oil",
      "Verdant Oil",
      "Violet Oil",
    ],
    name: "Oills",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9Hb2xkZW5PaWwiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/69094a06e9/GoldenOil.png",
  },
  scarabFilter: {
    items: [
      "Winged Reliquary Scarab",
      "Winged Divination Scarab",
      "Winged Breach Scarab",
      "Winged Abyss Scarab",
      "Winged Ambush Scarab",
      "Winged Harbinger Scarab",
      "Winged Expedition Scarab",
      "Winged Legion Scarab",
      "Winged Blight Scarab",
      "Fenumal Lure",
      "Gilded Expedition Scarab",
      "Farric Lure",
      "Craicic Lure",
      "Winged Bestiary Scarab",
      "Polished Expedition Scarab",
      "Gilded Harbinger Scarab",
      "Winged Cartography Scarab",
      "Rusted Expedition Scarab",
      "Gilded Ambush Scarab",
      "Winged Sulphite Scarab",
      "Winged Metamorph Scarab",
      "Winged Shaper Scarab",
      "Winged Elder Scarab",
      "Winged Torment Scarab",
      "Gilded Divination Scarab",
      "Saqawine Lure",
      "Gilded Abyss Scarab",
      "Gilded Blight Scarab",
      "Gilded Breach Scarab",
      "Polished Harbinger Scarab",
      "Gilded Bestiary Scarab",
      "Polished Ambush Scarab",
      "Gilded Reliquary Scarab",
      "Gilded Legion Scarab",
      "Gilded Metamorph Scarab",
      "Rusted Ambush Scarab",
      "Rusted Harbinger Scarab",
      "Gilded Sulphite Scarab",
      "Gilded Cartography Scarab",
      "Polished Legion Scarab",
      "Rusted Blight Scarab",
      "Polished Blight Scarab",
      "Rusted Bestiary Scarab",
      "Rusted Sulphite Scarab",
      "Polished Sulphite Scarab",
      "Polished Breach Scarab",
      "Gilded Torment Scarab",
      "Gilded Shaper Scarab",
      "Polished Cartography Scarab",
      "Polished Bestiary Scarab",
      "Gilded Elder Scarab",
      "Polished Divination Scarab",
      "Polished Reliquary Scarab",
      "Rusted Legion Scarab",
      "Rusted Metamorph Scarab",
      "Polished Metamorph Scarab",
      "Polished Abyss Scarab",
      "Rusted Abyss Scarab",
      "Rusted Cartography Scarab",
      "Rusted Divination Scarab",
      "Rusted Reliquary Scarab",
      "Rusted Elder Scarab",
      "Rusted Torment Scarab",
      "Rusted Breach Scarab",
      "Rusted Shaper Scarab",
      "Polished Shaper Scarab",
      "Polished Torment Scarab",
      "Polished Elder Scarab",
    ],
    name: "Scarabs",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9UaWVyNFNjYXJhYkhhcmJpbmdlcnMiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/81caefbf3f/Tier4ScarabHarbingers.png",
  },
  highScarabFilter: {
    items: [
      "Gilded Divination Scarab",
      "Gilded Reliquary Scarab",
      "Gilded Harbinger Scarab",
      "Gilded Ambush Scarab",
      "Gilded Breach Scarab",
      "Gilded Abyss Scarab",
      "Gilded Expedition Scarab",
      "Gilded Legion Scarab",
      "Gilded Bestiary Scarab",
      "Gilded Blight Scarab",
      "Gilded Cartography Scarab",
      "Gilded Sulphite Scarab",
      "Gilded Metamorph Scarab",
      "Gilded Torment Scarab",
      "Gilded Shaper Scarab",
      "Gilded Elder Scarab",
      "Winged Divination Scarab",
      "Winged Reliquary Scarab",
      "Winged Harbinger Scarab",
      "Winged Ambush Scarab",
      "Winged Breach Scarab",
      "Winged Abyss Scarab",
      "Winged Expedition Scarab",
      "Winged Legion Scarab",
      "Winged Bestiary Scarab",
      "Winged Blight Scarab",
      "Winged Cartography Scarab",
      "Winged Sulphite Scarab",
      "Winged Metamorph Scarab",
      "Winged Torment Scarab",
      "Winged Shaper Scarab",
      "Winged Elder Scarab",
    ],
    name: "High Scarabs",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9HcmVhdGVyU2NhcmFiSGFyYmluZ2VycyIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/ce393cfd58/GreaterScarabHarbingers.png",
  },
  fossilFilter: {
    items: [
      "Aberrant Fossil",
      "Aetheric Fossil",
      "Bloodstained Fossil",
      "Bound Fossil",
      "Corroded Fossil",
      "Deft Fossil",
      "Dense Fossil",
      "Faceted Fossil",
      "Fractured Fossil",
      "Frigid Fossil",
      "Fundamental Fossil",
      "Gilded Fossil",
      "Glyphic Fossil",
      "Hollow Fossil",
      "Jagged Fossil",
      "Lucent Fossil",
      "Metallic Fossil",
      "Perfect Fossil",
      "Prismatic Fossil",
      "Pristine Fossil",
      "Sanctified Fossil",
      "Scorched Fossil",
      "Serrated Fossil",
      "Shuddering Fossil",
      "Tangled Fossil",
    ],
    name: "Fossils",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRGVsdmUvRmFjZXRlZEZvc3NpbCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/db0aba6238/FacetedFossil.png",
  },
  essenceFilter: {
    items: [
      "Essence of Horror",
      "Essence of Hysteria",
      "Essence of Delirium",
      "Essence of Insanity",
      "Deafening Essence of Contempt",
      "Deafening Essence of Scorn",
      "Deafening Essence of Spite",
      "Deafening Essence of Wrath",
      "Deafening Essence of Rage",
      "Deafening Essence of Woe",
      "Deafening Essence of Dread",
      "Deafening Essence of Envy",
      "Deafening Essence of Greed",
      "Deafening Essence of Zeal",
      "Deafening Essence of Hatred",
      "Deafening Essence of Loathing",
      "Deafening Essence of Misery",
      "Deafening Essence of Sorrow",
      "Deafening Essence of Doubt",
      "Deafening Essence of Fear",
      "Shrieking Essence of Contempt",
      "Shrieking Essence of Scorn",
      "Shrieking Essence of Wrath",
      "Shrieking Essence of Greed",
      "Shrieking Essence of Spite",
      "Shrieking Essence of Woe",
      "Deafening Essence of Anger",
      "Deafening Essence of Anguish",
      "Deafening Essence of Suffering",
      "Deafening Essence of Torment",
      "Shrieking Essence of Dread",
      "Shrieking Essence of Envy",
      "Shrieking Essence of Rage",
      "Shrieking Essence of Sorrow",
      "Shrieking Essence of Zeal",
      "Muttering Essence of Anger",
      "Muttering Essence of Contempt",
      "Muttering Essence of Fear",
      "Muttering Essence of Greed",
      "Muttering Essence of Hatred",
      "Muttering Essence of Sorrow",
      "Muttering Essence of Torment",
      "Muttering Essence of Woe",
      "Remnant of Corruption",
      "Screaming Essence of Anger",
      "Screaming Essence of Contempt",
      "Screaming Essence of Doubt",
      "Screaming Essence of Dread",
      "Screaming Essence of Envy",
      "Screaming Essence of Fear",
      "Screaming Essence of Greed",
      "Screaming Essence of Hatred",
      "Screaming Essence of Loathing",
      "Screaming Essence of Misery",
      "Screaming Essence of Rage",
      "Screaming Essence of Scorn",
      "Screaming Essence of Sorrow",
      "Screaming Essence of Spite",
      "Screaming Essence of Suffering",
      "Screaming Essence of Torment",
      "Screaming Essence of Woe",
      "Screaming Essence of Wrath",
      "Screaming Essence of Zeal",
      "Shrieking Essence of Anger",
      "Shrieking Essence of Anguish",
      "Shrieking Essence of Doubt",
      "Shrieking Essence of Fear",
      "Shrieking Essence of Hatred",
      "Shrieking Essence of Loathing",
      "Shrieking Essence of Misery",
      "Shrieking Essence of Suffering",
      "Shrieking Essence of Torment",
      "Wailing Essence of Anger",
      "Wailing Essence of Anguish",
      "Wailing Essence of Contempt",
      "Wailing Essence of Doubt",
      "Wailing Essence of Fear",
      "Wailing Essence of Greed",
      "Wailing Essence of Hatred",
      "Wailing Essence of Loathing",
      "Wailing Essence of Rage",
      "Wailing Essence of Sorrow",
      "Wailing Essence of Spite",
      "Wailing Essence of Suffering",
      "Wailing Essence of Torment",
      "Wailing Essence of Woe",
      "Wailing Essence of Wrath",
      "Wailing Essence of Zeal",
      "Weeping Essence of Anger",
      "Weeping Essence of Contempt",
      "Weeping Essence of Doubt",
      "Weeping Essence of Fear",
      "Weeping Essence of Greed",
      "Weeping Essence of Hatred",
      "Weeping Essence of Rage",
      "Weeping Essence of Sorrow",
      "Weeping Essence of Suffering",
      "Weeping Essence of Torment",
      "Weeping Essence of Woe",
      "Weeping Essence of Wrath",
      "Whispering Essence of Contempt",
      "Whispering Essence of Greed",
      "Whispering Essence of Hatred",
      "Whispering Essence of Woe",
      "Screaming Essence of Anguish",
    ],
    name: "Essences",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Ib3Jyb3IxIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/748d594bde/Horror1.png",
  },
  highEssenceFilter: {
    name: "High Essence",
    items: [
      "Shrieking Essence of Contempt",
      "Shrieking Essence of Greed",
      "Shrieking Essence of Wrath",
      "Shrieking Essence of Zeal",
      "Shrieking Essence of Dread",
      "Shrieking Essence of Envy",
      "Shrieking Essence of Hatred",
      "Shrieking Essence of Loathing",
      "Shrieking Essence of Rage",
      "Shrieking Essence of Scorn",
      "Shrieking Essence of Sorrow",
      "Shrieking Essence of Spite",
      "Shrieking Essence of Anger",
      "Shrieking Essence of Fear",
      "Shrieking Essence of Woe",
      "Shrieking Essence of Anguish",
      "Shrieking Essence of Doubt",
      "Shrieking Essence of Misery",
      "Shrieking Essence of Suffering",
      "Shrieking Essence of Torment",
      "Deafening Essence of Contempt",
      "Deafening Essence of Greed",
      "Deafening Essence of Wrath",
      "Deafening Essence of Zeal",
      "Deafening Essence of Dread",
      "Deafening Essence of Envy",
      "Deafening Essence of Hatred",
      "Deafening Essence of Loathing",
      "Deafening Essence of Rage",
      "Deafening Essence of Scorn",
      "Deafening Essence of Sorrow",
      "Deafening Essence of Spite",
      "Deafening Essence of Anger",
      "Deafening Essence of Fear",
      "Deafening Essence of Woe",
      "Deafening Essence of Anguish",
      "Deafening Essence of Doubt",
      "Deafening Essence of Misery",
      "Deafening Essence of Suffering",
      "Deafening Essence of Torment",
      "Essence of Insanity",
      "Essence of Horror",
      "Essence of Delirium",
      "Essence of Hysteria"
    ],
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaEZyYWdtZW50c0NoYW9zIiwic2NhbGUiOjF9XQ/4c99b7dd49/BreachFragmentsChaos.png",
  },

  incubatorFilter: {
    items: [
      "Geomancer's Incubator",
      "Time-Lost Incubator",
      "Thaumaturge's Incubator",
      "Diviner's Incubator",
      "Ornate Incubator",
      "Foreboding Incubator",
      "Infused Incubator",
      "Fragmented Incubator",
      "Singular Incubator",
      "Celestial Jeweller's Incubator",
      "Enchanted Incubator",
      "Cartographer's Incubator",
      "Skittering Incubator",
      "Fossilised Incubator",
      "Abyssal Incubator",
      "Mysterious Incubator",
      "Celestial Armoursmith's Incubator",
      "Otherworldly Incubator",
      "Obscured Incubator",
      "Decadent Incubator",
      "Celestial Blacksmith's Incubator",
      "Morphing Incubator",
      "Maddening Incubator",
      "Blighted Incubator",
      "Primal Incubator",
    ],
    name: "Incubators",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdWJhdGlvbi9JbmN1YmF0aW9uQXJtb3VyIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/637c41a730/IncubationArmour.png",
  },
  artifactFilter: {
    items: ["Burial Medallion", "Exotic Coinage", "Astragali", "Scrap Metal"],
    name: "Artifact",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbi9CYXJ0ZXJSZWZyZXNoQ3VycmVuY3kiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/bf3e6fbe8f/BarterRefreshCurrency.png",
  },

  blightRavagedMapFilter: {
    items: [
      "Blight-ravaged Ancient City Map",
      "Blight-ravaged Arachnid Nest Map",
      "Blight-ravaged Arachnid Nest Map",
      "Blight-ravaged Arcade Map",
      "Blight-ravaged Arsenal Map",
      "Blight-ravaged Arsenal Map",
      "Blight-ravaged Ashen Wood Map",
      "Blight-ravaged Ashen Wood Map",
      "Blight-ravaged Atoll Map",
      "Blight-ravaged Bazaar Map",
      "Blight-ravaged Bog Map",
      "Blight-ravaged Bone Crypt Map",
      "Blight-ravaged Bone Crypt Map",
      "Blight-ravaged Burial Chambers Map",
      "Blight-ravaged Burial Chambers Map",
      "Blight-ravaged Burial Chambers Map",
      "Blight-ravaged Caldera Map",
      "Blight-ravaged Caldera Map",
      "Blight-ravaged Canyon Map",
      "Blight-ravaged Canyon Map",
      "Blight-ravaged Canyon Map",
      "Blight-ravaged Castle Ruins Map",
      "Blight-ravaged Cemetery Map",
      "Blight-ravaged Cemetery Map",
      "Blight-ravaged Channel Map",
      "Blight-ravaged City Square Map",
      "Blight-ravaged City Square Map",
      "Blight-ravaged Cold River Map",
      "Blight-ravaged Cold River Map",
      "Blight-ravaged Colonnade Map",
      "Blight-ravaged Colonnade Map",
      "Blight-ravaged Coral Ruins Map",
      "Blight-ravaged Coral Ruins Map",
      "Blight-ravaged Courthouse Map",
      "Blight-ravaged Courthouse Map",
      "Blight-ravaged Courtyard Map",
      "Blight-ravaged Coves Map",
      "Blight-ravaged Coves Map",
      "Blight-ravaged Crimson Temple Map",
      "Blight-ravaged Crimson Township Map",
      "Blight-ravaged Crimson Township Map",
      "Blight-ravaged Cursed Crypt Map",
      "Blight-ravaged Cursed Crypt Map",
      "Blight-ravaged Dark Forest Map",
      "Blight-ravaged Defiled Cathedral Map",
      "Blight-ravaged Desert Map",
      "Blight-ravaged Dry Sea Map",
      "Blight-ravaged Dry Sea Map",
      "Blight-ravaged Dunes Map",
      "Blight-ravaged Dunes Map",
      "Blight-ravaged Dungeon Map",
      "Blight-ravaged Dungeon Map",
      "Blight-ravaged Estuary Map",
      "Blight-ravaged Estuary Map",
      "Blight-ravaged Forbidden Woods Map",
      "Blight-ravaged Foundry Map",
      "Blight-ravaged Foundry Map",
      "Blight-ravaged Gardens Map",
      "Blight-ravaged Ghetto Map",
      "Blight-ravaged Grave Trough Map",
      "Blight-ravaged Graveyard Map",
      "Blight-ravaged Iceberg Map",
      "Blight-ravaged Infested Valley Map",
      "Blight-ravaged Infested Valley Map",
      "Blight-ravaged Ivory Temple Map",
      "Blight-ravaged Laboratory Map",
      "Blight-ravaged Lair Map",
      "Blight-ravaged Leyline Map",
      "Blight-ravaged Leyline Map",
      "Blight-ravaged Lookout Map",
      "Blight-ravaged Mausoleum Map",
      "Blight-ravaged Mesa Map",
      "Blight-ravaged Mesa Map",
      "Blight-ravaged Mineral Pools Map",
      "Blight-ravaged Mineral Pools Map",
      "Blight-ravaged Moon Temple Map",
      "Blight-ravaged Museum Map",
      "Blight-ravaged Museum Map",
      "Blight-ravaged Necropolis Map",
      "Blight-ravaged Necropolis Map",
      "Blight-ravaged Orchard Map",
      "Blight-ravaged Overgrown Shrine Map",
      "Blight-ravaged Peninsula Map",
      "Blight-ravaged Plateau Map",
      "Blight-ravaged Plateau Map",
      "Blight-ravaged Plaza Map",
      "Blight-ravaged Port Map",
      "Blight-ravaged Port Map",
      "Blight-ravaged Precinct Map",
      "Blight-ravaged Precinct Map",
      "Blight-ravaged Primordial Blocks Map",
      "Blight-ravaged Primordial Blocks Map",
      "Blight-ravaged Primordial Pool Map",
      "Blight-ravaged Sepulchre Map",
      "Blight-ravaged Sepulchre Map",
      "Blight-ravaged Shipyard Map",
      "Blight-ravaged Shipyard Map",
      "Blight-ravaged Shore Map",
      "Blight-ravaged Shrine Map",
      "Blight-ravaged Silo Map",
      "Blight-ravaged Spider Lair Map",
      "Blight-ravaged Spider Lair Map",
      "Blight-ravaged Strand Map",
      "Blight-ravaged Sulphur Vents Map",
      "Blight-ravaged Thicket Map",
      "Blight-ravaged Thicket Map",
      "Blight-ravaged Toxic Sewer Map",
      "Blight-ravaged Underground River Map",
      "Blight-ravaged Underground Sea Map",
      "Blight-ravaged Underground Sea Map",
      "Blight-ravaged Underground Sea Map",
      "Blight-ravaged Villa Map",
      "Blight-ravaged Villa Map",
      "Blight-ravaged Volcano Map",
      "Blight-ravaged Wasteland Map",
      "Blight-ravaged Wasteland Map",
    ],
    name: "Blight Ravaged Maps",
    icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9EZWZpbGVkQ2F0aGVkcmFsIiwidyI6MSwiaCI6MSwic2NhbGUiOjEsIm1uIjoxMywibXQiOjE2LCJtdWIiOnRydWV9XQ/88b6aa7f13/DefiledCathedral.png",
  },

  blightedMapFilter: {
    items: [
      "Blighted Acid Caverns Map",
      "Blighted Acid Caverns Map",
      "Blighted Acid Caverns Map",
      "Blighted Acid Caverns Map",
      "Blighted Alleyways Map",
      "Blighted Alleyways Map",
      "Blighted Alleyways Map",
      "Blighted Alleyways Map",
      "Blighted Alleyways Map",
      "Blighted Ancient City Map",
      "Blighted Arachnid Nest Map",
      "Blighted Arachnid Nest Map",
      "Blighted Arachnid Nest Map",
      "Blighted Arachnid Nest Map",
      "Blighted Arachnid Nest Map",
      "Blighted Arcade Map",
      "Blighted Arcade Map",
      "Blighted Arcade Map",
      "Blighted Arsenal Map",
      "Blighted Arsenal Map",
      "Blighted Arsenal Map",
      "Blighted Arsenal Map",
      "Blighted Ashen Wood Map",
      "Blighted Ashen Wood Map",
      "Blighted Atoll Map",
      "Blighted Atoll Map",
      "Blighted Atoll Map",
      "Blighted Atoll Map",
      "Blighted Atoll Map",
      "Blighted Bazaar Map",
      "Blighted Bazaar Map",
      "Blighted Bazaar Map",
      "Blighted Bog Map",
      "Blighted Bog Map",
      "Blighted Bog Map",
      "Blighted Bog Map",
      "Blighted Bone Crypt Map",
      "Blighted Bone Crypt Map",
      "Blighted Bone Crypt Map",
      "Blighted Bone Crypt Map",
      "Blighted Bone Crypt Map",
      "Blighted Burial Chambers Map",
      "Blighted Burial Chambers Map",
      "Blighted Burial Chambers Map",
      "Blighted Burial Chambers Map",
      "Blighted Cage Map",
      "Blighted Cage Map",
      "Blighted Cage Map",
      "Blighted Cage Map",
      "Blighted Cage Map",
      "Blighted Cage Map",
      "Blighted Caldera Map",
      "Blighted Caldera Map",
      "Blighted Caldera Map",
      "Blighted Caldera Map",
      "Blighted Caldera Map",
      "Blighted Canyon Map",
      "Blighted Canyon Map",
      "Blighted Canyon Map",
      "Blighted Castle Ruins Map",
      "Blighted Castle Ruins Map",
      "Blighted Castle Ruins Map",
      "Blighted Castle Ruins Map",
      "Blighted Castle Ruins Map",
      "Blighted Cemetery Map",
      "Blighted Cemetery Map",
      "Blighted Cemetery Map",
      "Blighted Channel Map",
      "Blighted Channel Map",
      "Blighted Channel Map",
      "Blighted City Square Map",
      "Blighted City Square Map",
      "Blighted City Square Map",
      "Blighted City Square Map",
      "Blighted Cold River Map",
      "Blighted Cold River Map",
      "Blighted Cold River Map",
      "Blighted Colonnade Map",
      "Blighted Colonnade Map",
      "Blighted Colonnade Map",
      "Blighted Coral Ruins Map",
      "Blighted Coral Ruins Map",
      "Blighted Coral Ruins Map",
      "Blighted Coral Ruins Map",
      "Blighted Coral Ruins Map",
      "Blighted Courthouse Map",
      "Blighted Courthouse Map",
      "Blighted Courthouse Map",
      "Blighted Courtyard Map",
      "Blighted Courtyard Map",
      "Blighted Courtyard Map",
      "Blighted Courtyard Map",
      "Blighted Coves Map",
      "Blighted Coves Map",
      "Blighted Coves Map",
      "Blighted Coves Map",
      "Blighted Coves Map",
      "Blighted Crimson Temple Map",
      "Blighted Crimson Temple Map",
      "Blighted Crimson Temple Map",
      "Blighted Crimson Temple Map",
      "Blighted Crimson Temple Map",
      "Blighted Crimson Township Map",
      "Blighted Crimson Township Map",
      "Blighted Crimson Township Map",
      "Blighted Crimson Township Map",
      "Blighted Cursed Crypt Map",
      "Blighted Cursed Crypt Map",
      "Blighted Cursed Crypt Map",
      "Blighted Dark Forest Map",
      "Blighted Dark Forest Map",
      "Blighted Dark Forest Map",
      "Blighted Defiled Cathedral Map",
      "Blighted Defiled Cathedral Map",
      "Blighted Defiled Cathedral Map",
      "Blighted Desert Map",
      "Blighted Desert Map",
      "Blighted Desert Map",
      "Blighted Dry Sea Map",
      "Blighted Dry Sea Map",
      "Blighted Dry Sea Map",
      "Blighted Dunes Map",
      "Blighted Dunes Map",
      "Blighted Dungeon Map",
      "Blighted Dungeon Map",
      "Blighted Dungeon Map",
      "Blighted Dungeon Map",
      "Blighted Dungeon Map",
      "Blighted Estuary Map",
      "Blighted Estuary Map",
      "Blighted Estuary Map",
      "Blighted Estuary Map",
      "Blighted Forbidden Woods Map",
      "Blighted Forbidden Woods Map",
      "Blighted Forbidden Woods Map",
      "Blighted Forking River Map",
      "Blighted Forking River Map",
      "Blighted Forking River Map",
      "Blighted Forking River Map",
      "Blighted Foundry Map",
      "Blighted Foundry Map",
      "Blighted Gardens Map",
      "Blighted Gardens Map",
      "Blighted Gardens Map",
      "Blighted Gardens Map",
      "Blighted Ghetto Map",
      "Blighted Grave Trough Map",
      "Blighted Grave Trough Map",
      "Blighted Grave Trough Map",
      "Blighted Graveyard Map",
      "Blighted Haunted Mansion Map",
      "Blighted Haunted Mansion Map",
      "Blighted Haunted Mansion Map",
      "Blighted Haunted Mansion Map",
      "Blighted Haunted Mansion Map",
      "Blighted Iceberg Map",
      "Blighted Iceberg Map",
      "Blighted Iceberg Map",
      "Blighted Iceberg Map",
      "Blighted Iceberg Map",
      "Blighted Infested Valley Map",
      "Blighted Infested Valley Map",
      "Blighted Infested Valley Map",
      "Blighted Infested Valley Map",
      "Blighted Infested Valley Map",
      "Blighted Ivory Temple Map",
      "Blighted Ivory Temple Map",
      "Blighted Ivory Temple Map",
      "Blighted Ivory Temple Map",
      "Blighted Laboratory Map",
      "Blighted Laboratory Map",
      "Blighted Laboratory Map",
      "Blighted Laboratory Map",
      "Blighted Lair Map",
      "Blighted Lair Map",
      "Blighted Lair Map",
      "Blighted Lava Lake Map",
      "Blighted Lava Lake Map",
      "Blighted Lava Lake Map",
      "Blighted Lava Lake Map",
      "Blighted Lava Lake Map",
      "Blighted Leyline Map",
      "Blighted Leyline Map",
      "Blighted Leyline Map",
      "Blighted Leyline Map",
      "Blighted Lookout Map",
      "Blighted Lookout Map",
      "Blighted Lookout Map",
      "Blighted Lookout Map",
      "Blighted Mausoleum Map",
      "Blighted Mausoleum Map",
      "Blighted Mausoleum Map",
      "Blighted Mausoleum Map",
      "Blighted Mausoleum Map",
      "Blighted Mesa Map",
      "Blighted Mesa Map",
      "Blighted Mesa Map",
      "Blighted Mineral Pools Map",
      "Blighted Mineral Pools Map",
      "Blighted Mineral Pools Map",
      "Blighted Mineral Pools Map",
      "Blighted Mineral Pools Map",
      "Blighted Mineral Pools Map",
      "Blighted Moon Temple Map",
      "Blighted Moon Temple Map",
      "Blighted Moon Temple Map",
      "Blighted Moon Temple Map",
      "Blighted Museum Map",
      "Blighted Museum Map",
      "Blighted Museum Map",
      "Blighted Museum Map",
      "Blighted Museum Map",
      "Blighted Necropolis Map",
      "Blighted Necropolis Map",
      "Blighted Necropolis Map",
      "Blighted Necropolis Map",
      "Blighted Orchard Map",
      "Blighted Orchard Map",
      "Blighted Overgrown Shrine Map",
      "Blighted Overgrown Shrine Map",
      "Blighted Overgrown Shrine Map",
      "Blighted Overgrown Shrine Map",
      "Blighted Peninsula Map",
      "Blighted Peninsula Map",
      "Blighted Peninsula Map",
      "Blighted Peninsula Map",
      "Blighted Peninsula Map",
      "Blighted Peninsula Map",
      "Blighted Plateau Map",
      "Blighted Plateau Map",
      "Blighted Plateau Map",
      "Blighted Plateau Map",
      "Blighted Plateau Map",
      "Blighted Plaza Map",
      "Blighted Plaza Map",
      "Blighted Plaza Map",
      "Blighted Port Map",
      "Blighted Port Map",
      "Blighted Port Map",
      "Blighted Port Map",
      "Blighted Port Map",
      "Blighted Precinct Map",
      "Blighted Precinct Map",
      "Blighted Precinct Map",
      "Blighted Precinct Map",
      "Blighted Precinct Map",
      "Blighted Primordial Blocks Map",
      "Blighted Primordial Blocks Map",
      "Blighted Primordial Blocks Map",
      "Blighted Primordial Blocks Map",
      "Blighted Primordial Pool Map",
      "Blighted Primordial Pool Map",
      "Blighted Primordial Pool Map",
      "Blighted Promenade Map",
      "Blighted Promenade Map",
      "Blighted Promenade Map",
      "Blighted Promenade Map",
      "Blighted Promenade Map",
      "Blighted Promenade Map",
      "Blighted Sepulchre Map",
      "Blighted Sepulchre Map",
      "Blighted Sepulchre Map",
      "Blighted Sepulchre Map",
      "Blighted Shipyard Map",
      "Blighted Shipyard Map",
      "Blighted Shipyard Map",
      "Blighted Shore Map",
      "Blighted Shore Map",
      "Blighted Shore Map",
      "Blighted Shore Map",
      "Blighted Shore Map",
      "Blighted Shrine Map",
      "Blighted Shrine Map",
      "Blighted Shrine Map",
      "Blighted Silo Map",
      "Blighted Silo Map",
      "Blighted Silo Map",
      "Blighted Silo Map",
      "Blighted Spider Forest Map",
      "Blighted Spider Forest Map",
      "Blighted Spider Forest Map",
      "Blighted Spider Forest Map",
      "Blighted Spider Lair Map",
      "Blighted Spider Lair Map",
      "Blighted Spider Lair Map",
      "Blighted Spider Lair Map",
      "Blighted Spider Lair Map",
      "Blighted Strand Map",
      "Blighted Strand Map",
      "Blighted Strand Map",
      "Blighted Strand Map",
      "Blighted Strand Map",
      "Blighted Sulphur Vents Map",
      "Blighted Sulphur Vents Map",
      "Blighted Sulphur Vents Map",
      "Blighted Sulphur Vents Map",
      "Blighted Sulphur Vents Map",
      "Blighted Temple Map",
      "Blighted Temple Map",
      "Blighted Temple Map",
      "Blighted Temple Map",
      "Blighted Thicket Map",
      "Blighted Thicket Map",
      "Blighted Thicket Map",
      "Blighted Thicket Map",
      "Blighted Thicket Map",
      "Blighted Toxic Sewer Map",
      "Blighted Underground River Map",
      "Blighted Underground River Map",
      "Blighted Underground River Map",
      "Blighted Underground Sea Map",
      "Blighted Underground Sea Map",
      "Blighted Underground Sea Map",
      "Blighted Villa Map",
      "Blighted Villa Map",
      "Blighted Villa Map",
      "Blighted Villa Map",
      "Blighted Volcano Map",
      "Blighted Volcano Map",
      "Blighted Volcano Map",
      "Blighted Volcano Map",
      "Blighted Wasteland Map",
      "Blighted Wasteland Map",
      "Blighted Wasteland Map",
      "Blighted Wasteland Map"
    ],
    name: "Blighted Maps",
    icon: "https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9Gb3JraW5nUml2ZXIiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MSwibW4iOjExLCJtdCI6MTUsIm1iIjp0cnVlfV0/d14b4572d0/ForkingRiver.png",
  },
  deliriumOrbFilter: {
    items: [
      "Skittering Delirium Orb",
      "Cartographer's Delirium Orb",
      "Diviner's Delirium Orb",
      "Fossilised Delirium Orb",
      "Thaumaturge's Delirium Orb",
      "Fine Delirium Orb",
      "Amorphous Delirium Orb",
      "Obscured Delirium Orb",
      "Foreboding Delirium Orb",
      "Singular Delirium Orb",
      "Blighted Delirium Orb",
      "Timeless Delirium Orb",
      "Fragmented Delirium Orb",
      "Whispering Delirium Orb",
      "Imperial Delirium Orb",
      "Jeweller's Delirium Orb",
      "Abyssal Delirium Orb",
      "Armoursmith's Delirium Orb",
      "Blacksmith's Delirium Orb",
    ],
    name: "Delirium Orbs",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRGVsaXJpdW0vRGVsaXJpdW1PcmJTY2FyYWJzIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/fa4c5160ca/DeliriumOrbScarabs.png",
  },
  invitationFilter: {
    items: [
      "Incandescent Invitation",
      "Screaming Invitation",
      "Maven's Invitation: The Elderslayers",
      "Maven's Invitation: The Formed",
      "Maven's Invitation: The Twisted",
      "Maven's Invitation: The Forgotten",
      "Maven's Invitation: The Hidden",
      "Polaric Invitation",
      "Maven's Invitation: The Feared",
      "Writhing Invitation",
      "Maven's Invitation: The Atlas"
    ],
    name: "Invitation",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQXRsYXMvTnVsbFZvaWQyIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/3c5b06022e/NullVoid2.png",
  },
  beastFilter: {
    items: [
      "Bleached Crawler",
      "Craicic Chimeral",
      "Farric Tiger Alpha",
      "Fenumal Plagued Arachnid",
      "Farrul, First of the Plains",
      "Parasite",
      "Fenumus, First of the Night",
      "Saqawine Rhex",
      "Craicic Maw",
      "Craiceann, First of the Deep",
      "Merveil's Favoured",
      "Fenumal Hybrid Arachnid",
      "Saqawal, First of the Sky",
      "Saqawine Cobra",
      "Farric Wolf Alpha",
      "Farric Lynx Alpha",
      "Rotting Vulture",
      "Saqawine Vulture",
      "Adolescent Rhex",
      "Craicic Spider Crab",
      "Avalanche Rider",
      "Craicic Vassal",
      "Escaped Rhex",
      "Pitbull Demon",
      "Infested Rhoa",
      "Spitting Parasite",
      "Craicic Savage Crab",
      "Farric Frost Hellion Alpha",
      "Craicic Watcher",
      "Merveil's Chosen",
      "Stygian Ape",
      "Freezing Wolf",
      "Hairy Bonecruncher",
      "Predatory Scorpion",
      "Brine Vassal",
      "Spindle Spider",
      "Leaping Spider",
      "Fenumal Queen",
      "Fenumal Devourer",
      "Farric Pit Hound",
      "Saqawine Blood Viper",
      "Fenumal Scrabbler",
      "Barb Serpent",
      "Savage Crab",
      "Purge Hound",
      "Murk Runner",
      "Vicious Parasite",
      "Forest Beast",
      "Shaggy Monstrosity",
      "Sewage Crawler",
      "Maternal Rhex",
      "Blood Chieftain",
      "Chrome-touched Chimeral",
      "Corrupted Rhoa",
      "Farric Ape",
      "Black Scorpion",
      "Enraptured Beast",
      "Bone Cruncher",
      "Cursed Spawn",
      "Farric Goliath",
      "Fenumal Scorpion",
      "Vaulting Croaker",
      "Sand Skitterer",
      "Mountain Hellion Alpha",
      "Fetid Maw",
      "Echo of the Verdant",
      "Alpine Shaman",
      "Bone Rhoa",
      "Elder-Blessed Rhoa",
      "Elder-Blessed Hellion",
      "Elder-Blessed Goatman",
      "Crypt Ambusher",
      "Elder-Blessed Cobra",
      "Lurking Venom",
      "Enraptured Crab",
      "Scum Crawler",
      "Farric Magma Hound",
      "Farric Flame Hellion Alpha",
      "Flame Hellion",
      "Avian Retch",
      "Dune Hellion",
      "Carrion Queen",
      "Porcupine Goliath",
      "Mountain Lynx",
      "Alpine Devil",
      "Mountain Hellion",
      "Rhoa Mare",
      "Mindless Scavenger",
      "Chimeric Croaker",
      "Carrion Swarmer",
      "Plummeting Ursa",
      "Chrome-touched Goliath",
      "Carrion Burrower",
      "Host Chieftain",
      "Corrupted Beast",
      "Cave Beast",
      "Carnage Ape",
      "Fury Hound",
      "Goatman Shaman",
      "Gravel Eater",
      "Plated Parasite",
      "Colossus Crusher",
      "Dust Scrabbler",
      "Grazing Taurus",
      "Gluttonous Gull",
      "Barrow Ape",
      "Scavenging Vulture",
      "Spine Serpent",
      "Merveil's Blessed",
      "Night Adder",
      "Glade Mamba",
      "Scalding Arachnid",
      "Bearded Devil",
      "Merveil's Attendant",
      "Arakaali's Daughter",
      "Plumed Chimeral",
      "Obsidian Eater",
      "Talon Archer",
      "Bramble Cobra",
      "Tercel Rhoa",
      "Chrome-touched Croaker",
      "Chrome-infused Croaker",
      "Hybrid Arachnid",
      "Carnage Chieftain",
      "Infested Crab",
      "Dread Primate",
      "Blood Ape",
      "Singing Siren",
      "Snow Wolf",
      "Ink Spinner",
      "Infested Tunnelfiend",
      "Goatman",
      "Bearded Shaman",
      "Chrome-infused Chimeral",
      "Cave Skitterer",
      "Venomous Spawn",
      "Webbed Spider",
      "Virulent Spider",
      "Enraptured Arachnid",
      "Corrupted Arach",
      "Crustacean Sniper",
      "Infested Ape",
      "Merveil's Retainer",
      "Host Cobra",
      "Sulphuric Scorpion",
      "Soulless Watcher",
      "Rooster Fiend",
      "Bearded Skycaller",
      "Infested Skitterer",
      "Goatman Fire-raiser",
      "Acid Slitherer",
      "Host Adder",
      "Skeletal Beast",
      "Farric Taurus",
      "Fenumal Widow",
      "Sand Leaper",
      "Chrome-infused Goliath",
      "Granite Eater",
      "Plagued Arachnid",
      "Noxious Tarantula",
      "Rock Spitter",
      "Ruins Hellion",
      "Mutant Arach",
      "Craicic Sand Spitter",
      "Farric Chieftain",
      "Infested Maw",
      "Hill Devil",
      "Devourer",
      "Shackled Hellion",
      "Fighting Bull",
      "Saqawine Rhoa",
      "Saqawine Chimeral",
      "Enslaved Hellion",
      "Dirt Scrabbler",
      "Craicic Squid",
      "Farric Ursa",
      "Saqawine Retch",
      "Craicic Shield Crab",
      "Farric Gargantuan",
      "Farric Goatman",
    ],
    name: "Beasts",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQmVzdGlhcnlPcmJGdWxsIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/3214b44360/BestiaryOrbFull.png",
  },
  resonatorFilter: {
    items: [
      "Prime Chaotic Resonator",
      "Prime Alchemical Resonator",
      "Powerful Chaotic Resonator",
      "Powerful Alchemical Resonator",
      "Potent Alchemical Resonator",
      "Potent Chaotic Resonator",
      "Primitive Chaotic Resonator",
      "Primitive Alchemical Resonator",
    ],
    name: "Resonators",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRGVsdmUvUmVyb2xsMngyQyIsInciOjIsImgiOjIsInNjYWxlIjoxfV0/584267701b/Reroll2x2C.png",
  },
  divinationFilter: {
    items: [
      "The Apothecary",
      "House of Mirrors",
      "The Price of Devotion",
      "The Insane Cat",
      "The Doctor",
      "Unrequited Love",
      "The Demon",
      "The Fiend",
      "Brother's Gift",
      "The Immortal",
      "The Shieldbearer",
      "Love Through Ice",
      "The Nurse",
      "Fire Of Unknown Origin",
      "The Price of Loyalty",
      "The Chosen",
      "The Cheater",
      "The Endless Darkness",
      "Seven Years Bad Luck",
      "The Sephirot",
      "Wealth and Power",
      "Choking Guilt",
      "The Soul",
      "Beauty Through Death",
      "Doryani's Epiphany",
      "Divine Beauty",
      "Succor of the Sinless",
      "Desecrated Virtue",
      "The Dragon's Heart",
      "The Samurai's Eye",
      "The Enlightened",
      "Brother's Stash",
      "The Artist",
      "The Garish Power",
      "Darker Half",
      "The Patient",
      "Matryoshka",
      "Home",
      "Gemcutter's Mercy",
      "The Eye of Terror",
      "Broken Promises",
      "The Last One Standing",
      "The Sacrifice",
      "The Mind's Eyes",
      "The Fortunate",
      "Imperfect Memories",
      "A Fate Worse Than Death",
      "The Strategist",
      "Nook's Crown",
      "Monochrome",
      "The Gulf",
      "Luminous Trove",
      "Magnum Opus",
      "The Destination",
      "Eternal Bonds",
      "The Progeny of Lunaris",
      "Silence and Frost",
      "The Academic",
      "The Long Con",
      "The Shortcut",
      "Alluring Bounty",
      "The Hook",
      "The Rabbit's Foot",
      "The Hunger",
      "The World Eater",
      "The Greatest Intentions",
      "Deadly Joy",
      "Altered Perception",
      "Pride of the First Ones",
      "The Eye of the Dragon",
      "The Professor",
      "The Eldritch Decay",
      "Keeper's Corruption",
      "Winter's Embrace",
      "Something Dark",
      "Remembrance",
      "Azyran's Reward",
      "Draped in Dreams",
      "The Scout",
      "The Polymath",
      "Void of the Elements",
      "The Escape",
      "The Eternal War",
      "Rebirth and Renewal",
      "Abandoned Wealth",
      "Gift of Asenath",
      "Haunting Shadows",
      "Chaotic Disposition",
      "Hunter's Reward",
      "Mawr Blaidd",
      "Merciless Armament",
      "Pride Before the Fall",
      "The Cartographer",
      "The Incantation",
      "The Jester",
      "The Rabid Rhoa",
      "The Spoiled Prince",
      "The Union",
      "The Vast",
      "Tranquillity",
      "Left to Fate",
      "The Dreamer",
      "The Jeweller's Boon",
      "Perfection",
      "The Celestial Stone",
      "Harmony of Souls",
      "Boon of the First Ones",
      "The Twilight Moon",
      "The Cacophony",
      "The Messenger",
      "The Seeker",
      "Burning Blood",
      "Demigod's Wager",
      "Dark Dreams",
      "The Heroic Shot",
      "The Skeleton",
      "Akil's Prophecy",
      "The Damned",
      "The Old Man",
      "Underground Forest",
      "Etched in Blood",
      "The Fishmonger",
      "The White Knight",
      "A Familiar Call",
      "The Hive of Knowledge",
      "The Unexpected Prize",
      "The Bitter Blossom",
      "Brotherhood in Exile",
      "The Bear Woman",
      "Fateful Meeting",
      "The Astromancer",
      "Brush, Paint and Palette",
      "A Modest Request",
      "Dementophobia",
      "Lachrymal Necrosis",
      "Costly Curio",
      "Ambitious Obsession",
      "The Emptiness",
      "A Stone Perfected",
      "The Aspirant",
      "Desperate Crusade",
      "Justified Ambition",
      "Misery in Darkness",
      "Bijoux",
      "Judging Voices",
      "Duality",
      "From Bone to Ashes",
      "The Dungeon Master",
      "Astral Protection",
      "Checkmate",
      "The Leviathan",
      "The Enforcer",
      "The Wedding Gift",
      "The Forsaken",
      "The Cataclysm",
      "The Warlord",
      "The Wolverine",
      "Echoes of Love",
      "Reckless Ambition",
      "The Traitor",
      "Endless Night",
      "A Mother's Parting Gift",
      "Anarchy's Price",
      "Coveted Possession",
      "Death",
      "Dying Anguish",
      "Hubris",
      "Light and Truth",
      "Lost Worlds",
      "Lucky Deck",
      "The Brittle Emperor",
      "The Cursed King",
      "The Dark Mage",
      "The Drunken Aristocrat",
      "The Feast",
      "The Gentleman",
      "The Inventor",
      "The King's Heart",
      "The Oath",
      "The Offering",
      "The Pack Leader",
      "The Pact",
      "The Road to Power",
      "The Scavenger",
      "The Sigil",
      "The Siren",
      "The Survivalist",
      "The Thaumaturgist",
      "The Throne",
      "The Twins",
      "The Tyrant",
      "The Warden",
      "The Web",
      "The Wind",
      "Turn the Other Cheek",
      "Call to the First Ones",
      "The Porcupine",
      "The Opulent",
      "Rebirth",
      "The Insatiable",
      "Forbidden Power",
      "The Hale Heart",
      "The Master",
      "The Undaunted",
      "The Witch",
      "The Undisputed",
      "The Innocent",
      "Sambodhi's Vow",
      "Arrogance of the Vaal",
      "The Landing",
      "The Journey",
      "The Deep Ones",
      "Buried Treasure",
      "The Primordial",
      "The Wolf's Legacy",
      "The Side Quest",
      "Cameria's Cut",
      "The Bones",
      "Deathly Designs",
      "The Tinkerer's Table",
      "The Easy Stroll",
      "Council of Cats",
      "Prometheus' Armoury",
      "The Tumbleweed",
      "The Awakened",
      "Peaceful Moments",
      "Acclimatisation",
      "Dying Light",
      "The Enthusiasts",
      "The Card Sharp",
      "The Last Supper",
      "A Sea of Blue",
      "The Price of Prescience",
      "Guardian's Challenge",
      "Disdain",
      "Chasing Risk",
      "Parasitic Passengers",
      "The Magma Crab",
      "The One That Got Away",
      "The Brawny Battle Mage",
      "Azure Rage",
      "Man With Bear",
      "A Dusty Memory",
      "Rain Tempter",
      "The Surgeon",
      "The Valkyrie",
      "The Fool",
      "Gift of the Gemling Queen",
      "Last Hope",
      "The Betrayal",
      "No Traces",
      "The Life Thief",
      "The Offspring",
      "The Fox in the Brambles",
      "Triskaidekaphobia",
      "The Gladiator",
      "The Lord in Black",
      "The Finishing Touch",
      "The Forward Gaze",
      "The Archmage's Right Hand",
      "The Queen",
      "The Surveyor",
      "Atziri's Arsenal",
      "The Golden Era",
      "The Deal",
      "Audacity",
      "Boundless Realms",
      "Bowyer's Dream",
      "Cartographer's Delight",
      "Destined to Crumble",
      "Dialla's Subjugation",
      "Earth Drinker",
      "Emperor of Purity",
      "Gemcutter's Promise",
      "Grave Knowledge",
      "Heterochromia",
      "Hope",
      "Humility",
      "Loyalty",
      "Lysah's Respite",
      "Prosperity",
      "Rats",
      "Scholar of the Seas",
      "Shard of Fate",
      "The Arena Champion",
      "The Avenger",
      "The Body",
      "The Calling",
      "The Carrion Crow",
      "The Celestial Justicar",
      "The Conduit",
      "The Dapper Prodigy",
      "The Demoness",
      "The Doppelganger",
      "The Dragon",
      "The Encroaching Darkness",
      "The Explorer",
      "The Fletcher",
      "The Formless Sea",
      "The Fox",
      "The Gemcutter",
      "The Hoarder",
      "The Inoculated",
      "The Lich",
      "The Lion",
      "The Lunaris Priestess",
      "The Mercenary",
      "The Poet",
      "The Risk",
      "The Sun",
      "The Visionary",
      "The Void",
      "The Watcher",
      "The Wolf's Shadow",
      "The Wrath",
      "Thunderous Skies",
      "Treasure Hunter",
      "Vinia's Token",
      "The Coming Storm",
      "The Wolven King's Bite",
      "The Spark and the Flame",
      "Might is Right",
      "Struck by Lightning",
      "The Obscured",
      "The Deceiver",
      "The Breach",
      "Three Voices",
      "The Beast",
      "The Sword King's Salute",
      "The Fathomless Depths",
      "The Dreamland",
      "Immortal Resolve",
      "The Admirer",
      "The Darkest Dream",
      "The Wilted Rose",
      "The Price of Protection",
      "A Dab of Ink",
      "The Mad King",
      "The Lord of Celebration",
      "Dark Temptation",
      "Boon of Justice",
      "Vile Power",
      "More is Never Enough",
      "Divine Justice",
      "Baited Expectations",
      "The Craving",
      "A Note in the Wind",
      "The Journalist",
      "Unchained",
      "Cursed Words",
      "Society's Remorse",
      "The Whiteout",
      "Prejudice",
      "Sambodhi's Wisdom",
      "The Blessing of Moosh",
      "Terrible Secret of Space",
      "The Forgotten Treasure",
      "The Prince of Darkness",
      "The Catch",
      "The Tireless Extractor",
      "The Transformation",
      "Further Invention",
      "Broken Truce",
      "The Shepherd's Sandals",
      "Lethean Temptation",
      "Alivia's Grace",
      "Auspicious Ambitions",
      "The Return of the Rat",
      "Ever-Changing",
      "The Rusted Bard",
      "Soul Quenched",
      "Poisoned Faith",
      "A Chilling Wind",
      "The Ruthless Ceinture",
      "The Wolf",
      "The Stormcaller",
      "The Tower",
      "The Standoff",
      "The Master Artisan",
      "Alone in the Darkness",
      "Vanity",
      "The Ethereal",
      "The Rite of Elements",
      "The Harvester",
      "The Saint's Treasure",
      "Lucky Connections",
      "The Adventuring Spirit",
      "Three Faces in the Dark",
      "The Realm",
      "Blind Venture",
      "Doedre's Madness",
      "Emperor's Luck",
      "Glimmer of Hope",
      "Her Mask",
      "Hunter's Resolve",
      "Rain of Chaos",
      "The Aesthete",
      "The Battle Born",
      "The Chains that Bind",
      "The Endurance",
      "The Flora's Gift",
      "The Gambler",
      "The Hermit",
      "The Lover",
      "The One With All",
      "The Penitent",
      "The Scholar",
      "The Summoner",
      "The Trial",
      "Time-Lost Relic",
      "Volatile Power",
      "Mitts",
      "The Wretched",
      "Lingering Remnants",
      "The Blazing Fire",
      "The Puzzle",
      "The Army of Blood",
      "Thirst for Knowledge",
      "The Mountain",
      "The Cache",
      "Assassin's Favour",
      "Jack in the Box",
      "Lantador's Lost Love",
      "The Catalyst",
      "The King's Blade",
      "The Metalsmith's Gift",
      "The Scarred Meadow",
      "Imperial Legacy",
    ],
    name: "Divination Cards",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvRGl2aW5hdGlvbi9JbnZlbnRvcnlJY29uIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/f34bf8cbb5/InventoryIcon.png",
  },

  tattooFilter: {
    items: [
      "Tattoo of the Ramako Makanga",
      "Honoured Tattoo of the Wise",
      "Honoured Tattoo of the Berserker",
      "Tattoo of the Arohongui Makanga",
      "Honoured Tattoo of the Storm",
      "Honoured Tattoo of the Barbarian",
      "Honoured Tattoo of the Hatungo",
      "Tattoo of the Ngamahu Makanga",
      "Honoured Tattoo of the Flock",
      "Honoured Tattoo of the Hunter",
      "Honoured Tattoo of the Warlord",
      "Tattoo of the Tasalio Makanga",
      "Honoured Tattoo of the Pa",
      "Honoured Tattoo of the Mountain",
      "Tattoo of the Ramako Sniper",
      "Tattoo of the Tawhoa Herbalist",
      "Tattoo of the Ngamahu Warmonger",
      "Tattoo of the Tawhoa Makanga",
      "Tattoo of the Hinekora Makanga",
      "Honoured Tattoo of the Oak",
      "Tattoo of the Kitava Makanga",
      "Honoured Tattoo of the Tuatara",
      "Tattoo of the Ramako Shaman",
      "Tattoo of the Valako Makanga",
      "Tattoo of the Tukohama Makanga",
      "Tattoo of the Tukohama Warcaller",
      "Honoured Tattoo of the Pillager",
      "Tattoo of the Ramako Fleetfoot",
      "Tattoo of the Valako Stormrider",
      "Honoured Tattoo of the Dove",
      "Tattoo of the Rongokurai Turtle",
      "Loyalty Tattoo of Rakiata",
      "Tattoo of the Rongokurai Makanga",
      "Tattoo of the Tasalio Scout",
      "Tattoo of the Tukohama Warmonger",
      "Loyalty Tattoo of Ahuana",
      "Loyalty Tattoo of Maata",
      "Loyalty Tattoo of Ikiaho",
      "Honoured Tattoo of the Flood",
      "Tattoo of the Rongokurai Warrior",
      "Tattoo of the Hinekora Shaman",
      "Tattoo of the Arohongui Moonwarden",
      "Tattoo of the Hinekora Storyteller",
      "Honoured Tattoo of the Turtle",
      "Tattoo of the Arohongui Shaman",
      "Tattoo of the Ngamahu Firewalker",
      "Tattoo of the Hinekora Warmonger",
      "Tattoo of the Kitava Shaman",
      "Loyalty Tattoo of Kiloava",
      "Tattoo of the Hinekora Warrior",
      "Tattoo of the Hinekora Deathwarden",
      "Tattoo of the Tukohama Warrior",
      "Tattoo of the Valako Scout",
      "Tattoo of the Ramako Archer",
      "Tattoo of the Arohongui Warrior",
      "Tattoo of the Valako Shieldbearer",
      "Honoured Tattoo of the Sky",
      "Tattoo of the Tawhoa Shaman",
      "Tattoo of the Ngamahu Shaman",
      "Tattoo of the Ngamahu Woodcarver",
      "Tattoo of the Tasalio Warrior",
      "Tattoo of the Kitava Warrior",
      "Tattoo of the Valako Shaman",
      "Loyalty Tattoo of Akoya",
      "Loyalty Tattoo of Kahuturoa",
      "Loyalty Tattoo of Utula",
      "Loyalty Tattoo of Kaom",
      "Tattoo of the Rongokurai Goliath",
      "Tattoo of the Tawhoa Naturalist",
      "Tattoo of the Valako Warrior",
      "Tattoo of the Tukohama Shaman",
      "Tattoo of the Tasalio Bladedancer",
      "Tattoo of the Tasalio Shaman",
      "Tattoo of the Arohongui Scout",
      "Tattoo of the Tawhoa Warrior",
      "Tattoo of the Tawhoa Scout",
      "Tattoo of the Tukohama Brawler",
      "Tattoo of the Tasalio Tideshifter",
      "Tattoo of the Rongokurai Brute",
      "Tattoo of the Ngamahu Warrior",
      "Tattoo of the Ramako Scout",
      "Tattoo of the Rongokurai Guard",
      "Tattoo of the Arohongui Warmonger",
      "Tattoo of the Kitava Blood Drinker",
      "Tattoo of the Kitava Heart Eater",
      "Tattoo of the Kitava Rebel",
      "Loyalty Tattoo of Tawhanuku",
    ],
    name: "Tattoo ",
    icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQW5jZXN0b3JzL0NvbW1vbkRleFRhdHR0b29FcXVpcG1lbnQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/b80711f45f/CommonDexTatttooEquipment.png",
  },
};
