export const currencyFilter: string[] = [
  "Mirror of Kalandra",
  "Mirror Shard",
  "Tempering Orb",
  "Maven's Orb",
  "Awakener's Orb",
  "Hunter's Exalted Orb",
  "Tailoring Orb",
  "Exalted Orb",
  "Redeemer's Exalted Orb",
  "Warlord's Exalted Orb",
  "Prime Regrading Lens",
  "Secondary Regrading Lens",
  "Crusader's Exalted Orb",
  "Blessing of Chayula",
  "Blessing of Uul-Netol",
  "Divine Orb",
  "Ritual Vessel",
  "Blessing of Esh",
  "Ancient Orb",
  "Blessing of Xoph",
  "Blessing of Tul",
  "Orb of Unmaking",
  "Veiled Chaos Orb",
  "Orb of Annulment",
  "Unstable Catalyst",
  "Prismatic Catalyst",
  "Fertile Catalyst",
  "Harbinger's Orb",
  "Awakened Sextant",
  "Elevated Sextant",
  "Accelerating Catalyst",
  "Stacked Deck",
  "Tempering Catalyst",
  "Gemcutter's Prism",
  "Blessed Orb",
  "Prime Sextant",
  "Vaal Orb",
  "Orb of Scouring",
  "Orb of Regret",
  "Regal Orb",
  "Turbulent Catalyst",
  "Orb of Horizons",
  "Simple Sextant",
  "Abrasive Catalyst",
  "Intrinsic Catalyst",
  "Orb of Fusing",
  "Glassblower's Bauble",
  "Noxious Catalyst",
  "Orb of Alteration",
  "Cartographer's Chisel",
  "Imbued Catalyst",
  "Orb of Alchemy",
  "Orb of Binding",
  "Silver Coin",
  "Orb of Chance",
  "Chromatic Orb",
  "Orb of Augmentation",
  "Jeweller's Orb",
  "Armourer's Scrap",
  "Orb of Transmutation",
  "Blacksmith's Whetstone",
  "Engineer's Orb",
];
export const fragmentFilter: string[] = [
  "The Maven's Writ",
  "Chayula's Breachstone",
  "Chayula's Pure Breachstone",
  "Chayula's Charged Breachstone",
  "Chayula's Enriched Breachstone",
  "Fragment of Knowledge",
  "Fragment of Shape",
  "Simulacrum",
  "Uul-Netol's Pure Breachstone",
  "Timeless Maraketh Emblem",
  "Gift to the Goddess",
  "Xoph's Pure Breachstone",
  "Tul's Pure Breachstone",
  "Timeless Templar Emblem",
  "Esh's Pure Breachstone",
  "Uul-Netol's Enriched Breachstone",
  "Yriel's Key",
  "Volkuur's Key",
  "Xoph's Enriched Breachstone",
  "Tul's Enriched Breachstone",
  "Esh's Enriched Breachstone",
  "Uul-Netol's Charged Breachstone",
  "Inya's Key",
  "Eber's Key",
  "Fragment of Emptiness",
  "Fragment of Terror",
  "Uul-Netol's Breachstone",
  "Xoph's Charged Breachstone",
  "Fragment of Eradication",
  "Timeless Vaal Emblem",
  "Fragment of Purification",
  "Fragment of Enslavement",
  "Fragment of Constriction",
  "Esh's Charged Breachstone",
  "Tul's Charged Breachstone",
  "Fragment of the Chimera",
  "Crescent Splinter",
  "Fragment of the Minotaur",
  "Xoph's Breachstone",
  "Timeless Eternal Emblem",
  "Tul's Breachstone",
  "Timeless Karui Emblem",
  "Fragment of the Hydra",
  "Fragment of the Phoenix",
  "Mortal Ignorance",
  "Esh's Breachstone",
  "Mortal Rage",
  "Dedication to the Goddess",
  "Tribute to the Goddess",
  "Mortal Hope",
  "Mortal Grief",
  "Splinter of Chayula",
  "Divine Vessel",
  "Timeless Maraketh Splinter",
  "Timeless Templar Splinter",
  "Offering to the Goddess",
  "Splinter of Uul-Netol",
  "Sacrifice at Midnight",
  "Sacrifice at Noon",
  "Simulacrum Splinter",
  "Sacrifice at Dusk",
  "Sacrifice at Dawn",
  "Splinter of Xoph",
  "Splinter of Tul",
  "Splinter of Esh",
  "Timeless Karui Splinter",
  "Timeless Eternal Empire Splinter",
  "Timeless Vaal Splinter",
];
export const oilFilter: string[] = [
  "Tainted Oil",
  "Golden Oil",
  "Silver Oil",
  "Opalescent Oil",
  "Crimson Oil",
  "Black Oil",
  "Violet Oil",
  "Sepia Oil",
  "Verdant Oil",
  "Clear Oil",
  "Teal Oil",
  "Amber Oil",
  "Azure Oil",
  "Indigo Oil",
];
export const scarabFilter: string[] = [
  "Winged Ambush Scarab",
  "Winged Legion Scarab",
  "Winged Harbinger Scarab",
  "Craicic Lure",
  "Fenumal Lure",
  "Winged Abyss Scarab",
  "Winged Breach Scarab",
  "Winged Divination Scarab",
  "Winged Blight Scarab",
  "Winged Bestiary Scarab",
  "Winged Reliquary Scarab",
  "Gilded Ambush Scarab",
  "Gilded Legion Scarab",
  "Gilded Harbinger Scarab",
  "Winged Sulphite Scarab",
  "Winged Cartography Scarab",
  "Farric Lure",
  "Winged Shaper Scarab",
  "Winged Elder Scarab",
  "Gilded Bestiary Scarab",
  "Winged Metamorph Scarab",
  "Polished Legion Scarab",
  "Winged Perandus Scarab",
  "Winged Torment Scarab",
  "Gilded Breach Scarab",
  "Polished Ambush Scarab",
  "Gilded Abyss Scarab",
  "Gilded Blight Scarab",
  "Gilded Divination Scarab",
  "Rusted Legion Scarab",
  "Saqawine Lure",
  "Polished Harbinger Scarab",
  "Polished Bestiary Scarab",
  "Gilded Metamorph Scarab",
  "Gilded Sulphite Scarab",
  "Gilded Reliquary Scarab",
  "Gilded Cartography Scarab",
  "Polished Blight Scarab",
  "Polished Breach Scarab",
  "Rusted Blight Scarab",
  "Rusted Elder Scarab",
  "Polished Sulphite Scarab",
  "Polished Elder Scarab",
  "Gilded Elder Scarab",
  "Rusted Bestiary Scarab",
  "Rusted Harbinger Scarab",
  "Gilded Torment Scarab",
  "Gilded Shaper Scarab",
  "Gilded Perandus Scarab",
  "Polished Cartography Scarab",
  "Polished Divination Scarab",
  "Rusted Metamorph Scarab",
  "Polished Metamorph Scarab",
  "Rusted Cartography Scarab",
  "Rusted Breach Scarab",
  "Rusted Ambush Scarab",
  "Rusted Sulphite Scarab",
  "Polished Perandus Scarab",
  "Polished Abyss Scarab",
  "Rusted Divination Scarab",
  "Rusted Reliquary Scarab",
  "Rusted Torment Scarab",
  "Rusted Shaper Scarab",
  "Rusted Perandus Scarab",
  "Polished Shaper Scarab",
  "Polished Torment Scarab",
  "Polished Reliquary Scarab",
  "Rusted Abyss Scarab",
];
export const fossilFilter: string[] = [
  "Faceted Fossil",
  "Fractured Fossil",
  "Hollow Fossil",
  "Glyphic Fossil",
  "Bloodstained Fossil",
  "Sanctified Fossil",
  "Bound Fossil",
  "Gilded Fossil",
  "Prismatic Fossil",
  "Serrated Fossil",
  "Perfect Fossil",
  "Aetheric Fossil",
  "Corroded Fossil",
  "Shuddering Fossil",
  "Enchanted Fossil",
  "Tangled Fossil",
  "Dense Fossil",
  "Jagged Fossil",
  "Pristine Fossil",
  "Lucent Fossil",
  "Encrusted Fossil",
  "Aberrant Fossil",
  "Scorched Fossil",
  "Frigid Fossil",
  "Metallic Fossil",
];
export const essenceFilter: string[] = [
  "Essence of Horror",
  "Essence of Hysteria",
  "Essence of Delirium",
  "Essence of Insanity",
  "Deafening Essence of Contempt",
  "Deafening Essence of Scorn",
  "Deafening Essence of Spite",
  "Deafening Essence of Wrath",
  "Deafening Essence of Rage",
  "Deafening Essence of Woe",
  "Deafening Essence of Dread",
  "Deafening Essence of Envy",
  "Deafening Essence of Greed",
  "Deafening Essence of Zeal",
  "Deafening Essence of Hatred",
  "Deafening Essence of Loathing",
  "Deafening Essence of Misery",
  "Deafening Essence of Sorrow",
  "Deafening Essence of Doubt",
  "Deafening Essence of Fear",
  "Shrieking Essence of Contempt",
  "Shrieking Essence of Scorn",
  "Shrieking Essence of Wrath",
  "Shrieking Essence of Greed",
  "Shrieking Essence of Spite",
  "Shrieking Essence of Woe",
  "Deafening Essence of Anger",
  "Deafening Essence of Anguish",
  "Deafening Essence of Suffering",
  "Deafening Essence of Torment",
  "Shrieking Essence of Dread",
  "Shrieking Essence of Envy",
  "Shrieking Essence of Rage",
  "Shrieking Essence of Sorrow",
  "Shrieking Essence of Zeal",
  "Muttering Essence of Anger",
  "Muttering Essence of Contempt",
  "Muttering Essence of Fear",
  "Muttering Essence of Greed",
  "Muttering Essence of Hatred",
  "Muttering Essence of Sorrow",
  "Muttering Essence of Torment",
  "Muttering Essence of Woe",
  "Remnant of Corruption",
  "Screaming Essence of Anger",
  "Screaming Essence of Contempt",
  "Screaming Essence of Doubt",
  "Screaming Essence of Dread",
  "Screaming Essence of Envy",
  "Screaming Essence of Fear",
  "Screaming Essence of Greed",
  "Screaming Essence of Hatred",
  "Screaming Essence of Loathing",
  "Screaming Essence of Misery",
  "Screaming Essence of Rage",
  "Screaming Essence of Scorn",
  "Screaming Essence of Sorrow",
  "Screaming Essence of Spite",
  "Screaming Essence of Suffering",
  "Screaming Essence of Torment",
  "Screaming Essence of Woe",
  "Screaming Essence of Wrath",
  "Screaming Essence of Zeal",
  "Shrieking Essence of Anger",
  "Shrieking Essence of Anguish",
  "Shrieking Essence of Doubt",
  "Shrieking Essence of Fear",
  "Shrieking Essence of Hatred",
  "Shrieking Essence of Loathing",
  "Shrieking Essence of Misery",
  "Shrieking Essence of Suffering",
  "Shrieking Essence of Torment",
  "Wailing Essence of Anger",
  "Wailing Essence of Anguish",
  "Wailing Essence of Contempt",
  "Wailing Essence of Doubt",
  "Wailing Essence of Fear",
  "Wailing Essence of Greed",
  "Wailing Essence of Hatred",
  "Wailing Essence of Loathing",
  "Wailing Essence of Rage",
  "Wailing Essence of Sorrow",
  "Wailing Essence of Spite",
  "Wailing Essence of Suffering",
  "Wailing Essence of Torment",
  "Wailing Essence of Woe",
  "Wailing Essence of Wrath",
  "Wailing Essence of Zeal",
  "Weeping Essence of Anger",
  "Weeping Essence of Contempt",
  "Weeping Essence of Doubt",
  "Weeping Essence of Fear",
  "Weeping Essence of Greed",
  "Weeping Essence of Hatred",
  "Weeping Essence of Rage",
  "Weeping Essence of Sorrow",
  "Weeping Essence of Suffering",
  "Weeping Essence of Torment",
  "Weeping Essence of Woe",
  "Weeping Essence of Wrath",
  "Whispering Essence of Contempt",
  "Whispering Essence of Greed",
  "Whispering Essence of Hatred",
  "Whispering Essence of Woe",
  "Screaming Essence of Anguish",
];
